### ISSUE TITLE
antd-components/Upload default prop action

### ISSUE THREAD

**Issue by NotCoderJack** [alibaba/formily#1005]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

Why in file [Upload#L164](https://github.com/alibaba/formily/blob/master/packages/antd-components/src/upload/index.tsx#L164) ,  default `action` is a mock url which doesn't work now? And this may cause problem if user don't set `action` prop, which should not happen I think.
.

**Comment by NotCoderJack** [comment]
Why close this issue?

**Comment by janryWang** [comment]
这个在2.x中已经干掉mock地址了，1.x先不去掉
