### ISSUE TITLE
官网打不开了

### ISSUE THREAD

**Issue by huxiaosheng** [alibaba/formily#1015]

**Comment by anyuxuan** [comment]
![image](https://user-images.githubusercontent.com/24931869/93019307-c8f6a500-f608-11ea-8059-564f678dc392.png)
全部都Not Found了

**Comment by wmwgithub** [comment]
而且自己把源码拉去下来生成文档遇到了 Can't resolve 'fs'
Windows node version 12.18.3
![image](https://user-images.githubusercontent.com/34740295/93034932-40125480-f66e-11ea-943c-7fe97e047d43.png)

**Comment by liyaodong** [comment]
如果去除掉 ServiceWorker 的缓存就是这个样子了。。。
![image](https://user-images.githubusercontent.com/3196361/93035675-40135400-f670-11ea-9a03-d0f94be6a2d2.png)

**Comment by janryWang** [comment]
netlify网站续费断掉了，处理时间会比较慢，先直接在github的docs上看看，或者clone到本地来看吧
