### ISSUE TITLE
升级到最新版的antd和formily后报错：there are several instances of 'styled-components' initialized in this application

### ISSUE THREAD

**Issue by effapp** [alibaba/formily#1016]
您好：
升级到最新版的antd（4.6.4）和formily(1.3.2)后报错如下：
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process, missing theme prop, and makes your application bigger without a good reason
报错后，formily表单不能显示。

请问，这个问题应该如何解决？

**Comment by janryWang** [comment]
需要手动安装styled-components

**Comment by effapp** [comment]
umi下也有一个styled-components组件，执行npm dedupe后解决了。
