### ISSUE TITLE
@formily/next Form inline不生效，帮忙看下谢谢

### ISSUE THREAD

**Issue by mopsky** [alibaba/formily#1025]
**Describe the bug**
第一次用@formily/next，因为给的案例太少了，帮忙看下Form inline为什么不生效呢，是不是我写法有什么问题，谢谢

![image](https://user-images.githubusercontent.com/18085384/93748776-61a1ac00-fc2b-11ea-9a61-be442e730608.png)

**To Reproduce**
Please using Codesandbox
- [@formily/next bug report template](https://codesandbox.io/s/boring-dawn-tixps)
- [@formily/antd bug report template](https://codesandbox.io/s/lively-sky-pf5c3)

代码：https://codesandbox.io/s/formly-test-dtgh5

```
import React from "react";
import "./styles.css";
import { Input } from "@alifd/next";
import { Form, FormItem } from "@formily/next";
import "@alifd/next/dist/next.css";

export default function App() {
  return (
    <div>
      <Form inline>
        <FormItem name="aaa" addonTextBefore="aaa" component={Input} />
        <FormItem name="bbb" addonTextBefore="bbb" component={Input} />​
      </Form>
    </div>
  );
}

```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by janryWang** [comment]
styled-components版本保证是4.x即可

**Comment by mopsky** [comment]
> styled-components

啊，5.X的都不行么
