### ISSUE TITLE
'log' is not exported by node_modules/@formily/antd/esm/shared.js

### ISSUE THREAD

**Issue by lastIndexOf** [alibaba/formily#1033]
**Describe the bug**
@formily/antd/esm/shared.js  没有导出 `log` ， @formily/antd/esm/components/Form.js 却引入了这个变量，编译报错

**To Reproduce**
Please using Codesandbox
- [@formily/next bug report template](https://codesandbox.io/s/boring-dawn-tixps)
- [@formily/antd bug report template](https://codesandbox.io/s/lively-sky-pf5c3)

**Expected behavior**
不报错

**Screenshots**
![image](https://user-images.githubusercontent.com/13101975/94357898-4b826880-00cf-11eb-9648-eca6060808bf.png)

**Desktop (please complete the following information):**
 - OS: osX，10.15.4

**Comment by janryWang** [comment]
有导出log，你是怎么使用的，给个codesandbox看看

**Comment by lastIndexOf** [comment]
@janryWang 直接装下依赖之后 snowpack install，报上述错误，看了一下源码确实没有导出这个变量 
https://github.com/alibaba/formily/blob/master/packages/antd/src/shared.ts

**Comment by janryWang** [comment]
> @janryWang 直接装下依赖之后 snowpack install，报上述错误，看了一下源码确实没有导出这个变量
> https://github.com/alibaba/formily/blob/master/packages/antd/src/shared.ts

formily/shared这个包里有的 https://github.com/alibaba/formily/blob/master/packages/antd/src/shared.ts#L9
