### ISSUE TITLE
使用自增列表组件,去除操作列后报警告

### ISSUE THREAD

**Issue by lovehamburger** [alibaba/formily#1034]
这边使用next 自增列表组件后，想要去除操作列后 页面效果是成功了，但是开发者工具里面报警告，帮我看下哈

https://codesandbox.io/s/intelligent-gates-yh8de
这是案例

帮我看下哈

![image](https://user-images.githubusercontent.com/22336867/94357914-72409f00-00cf-11eb-81e5-bf5f76d390b8.png)

**Comment by janryWang** [comment]
没法复现

**Comment by lovehamburger** [comment]
是使用的next呢 ，这是新链接,你点开这个看下呢   https://codesandbox.io/s/formily-arraytable-8zyfw

**Comment by mopsky** [comment]
确实有同样的问题，antd的没警告，改成next就报错了
![image](https://user-images.githubusercontent.com/18085384/94358266-630f2080-00d2-11eb-801c-eae677651df5.png)
