### ISSUE TITLE
通过 JSON SCHEMA 实现国际化表单

### ISSUE THREAD

**Issue by sspku-yqLiu** [alibaba/formily#1038]
**Is your feature request related to a problem? Please describe.**
我们使用 formily 构建的表单需要支持多种语言:
https://github.com/ice-lab/iceworks/issues/574

**Describe the solution you'd like**
Formily 能否提供支持多语言的国际化方案

**Describe alternatives you've considered**
预处理 JSON SCHEMA 以完成语言加载

**Comment by janryWang** [comment]
formily天然支持国际化的，而且它需要处理语言的部分只有校验信息，没啥特殊的，校验默认文案是可以配的，具体看文档

**Comment by alvinhui** [comment]
@sspku-yqLiu ， @janryWang 所描述的「天然支持国际化」，意思应该是说传递 schema 的使用自己先确定好语言。

另外，「国际化」和「多语言」是两回事儿。

**Comment by sspku-yqLiu** [comment]
OK 这个场景的一个问题在于 schema 是存放在 json 文件中的， 不能直接使用国际化方案，预处理的方案应该比较好。

**Comment by xiazhiqiang** [comment]
文档地址：https://formilyjs.org/zh-CN/guide/advanced/validate#%E5%AE%9A%E5%88%B6%E6%A0%A1%E9%AA%8C%E6%96%87%E6%A1%88

```javascript
import {
  createForm,
  registerValidateLocale,
  setValidateLanguage,
} from '@formily/core'

setValidateLanguage('zh-CN');
```
以上可设置Formily默认的文案。
同时在应用中通过 ConfigProvider 设置lang属性包裹所有Fusion或Antd页面或组件即可。
