### ISSUE TITLE
@formily/antd-components 中的Select组件，设置mode='multiple'时，重置无效，点击删除无效

### ISSUE THREAD

**Issue by JxSx** [alibaba/formily#1042]
**Describe the bug**
`@formily/antd-components` 中的`Select`组件，设置`mode='multiple'`时，重置后，输入框中选中的标签依然存在，点击删除标签，依然回显标签

**To Reproduce**
- [@formily/antd bug report template](https://codesandbox.io/s/naughty-banach-7lmp0)

**Expected behavior**
期望点击“重置”，输入框清空。点击选项删除，输入框Tag回显正常

**Screenshots**
![image](https://user-images.githubusercontent.com/12441183/94653795-b7aed780-032e-11eb-8c7a-fab9b62c3db9.png)

**Comment by janryWang** [comment]
看了codesandbox没法复现
