### ISSUE TITLE
Schema中x-mega-props只有full才生效

### ISSUE THREAD

**Issue by goomadao** [alibaba/formily#1044]
**Describe the bug**
x-mega-props只有full才生效

**To Reproduce**

[Codesandbox](https://codesandbox.io/s/optimistic-black-1rdww?file=/index.js)

**Expected behavior**
labelAlign等也能生效

**Screenshots**
![image](https://user-images.githubusercontent.com/39483078/94716154-04230300-0381-11eb-9e12-1b41468dae67.png)

**Comment by quirkyshop** [comment]
外层需要写FormMegaLayout，x-mega的属性才能生效
