### ISSUE TITLE
拓展组件获取协议

### ISSUE THREAD

**Issue by laughing-pic-zhu** [alibaba/formily#1046]
**Is your feature request related to a problem? Please describe.**

x-component 能支持{x-component:'radio.button'} 自动获取Radio.Button 组件,目前只能手动注册Radio、和Radio.Button这两个组件

**Describe the solution you'd like**
类似 lodash get功能

**Describe alternatives you've considered**

**Additional context**

**Comment by janryWang** [comment]
2.x中已经支持
