### ISSUE TITLE
description的颜色没有重置

### ISSUE THREAD

**Issue by Rhuaer** [alibaba/formily#1053]
**Describe the bug**
FormItem的description的颜色没有重置

**To Reproduce**

- [@formily/antd bug](https://codesandbox.io/s/tender-williamson-e5deq)

1. 一开始可以看到description的文字是普通颜色
2. 点击查询，会显示校验错误的信息，校验提示文字是红色
3. 填入或者选择一些内容，desc恢复显示，但颜色还是错误状态的红色

**Expected behavior**

期望是description恢复显示后，颜色也是正常颜色，而不是错误状态的红色

**Screenshots**

![image](https://user-images.githubusercontent.com/13702561/97080174-14e73180-162c-11eb-956c-60b79706bb8a.png)

**Comment by Yohox** [comment]
#1071
