### ISSUE TITLE
内核可能还需要重构一次

### ISSUE THREAD

**Issue by janryWang** [alibaba/formily#1055]
目前内核状态管理主要存在几个问题：
1. FormGraph是一棵扁平树，很难直接映射DataTree和NodeTree的关系，导致在ArrayList场景的状态交换上计算量很大，同时有用户想直接操作FormGraph，现在也没有提供比较友好的API，原因就在于此
2. 字段渲染策略很脏，即便设计了hostRender机制，也不是一个比较智能化的渲染策略
3. 所有处理逻辑都是基于脏检测来实现的，脏检测始终还是存在性能瓶颈，优化到极限也还是一样

所以，我也在思考，Formily这样的表单解决方案的最佳内核实现到底应该是怎样的？

因为最近在深度使用mobx，完全沉迷于mobx各种精妙的设计，它的依赖收集机制，恰好可以让Formily真正彻底的放弃dirty check，所以，或许我们可以参考mobx的设计，将依赖收集机制加入进formily中。然后FormGraph的设计，或许可以放弃扁平树，改成真正的ObservableTree，比如：

```typescript
interface FormGraphNode {
   name:string,
   path:string,
   ...
   children:FormGraphChildren<FormGraphNode>
}
```

只要节点信息中包含了子节点信息，那这样做状态交换就会变得非常容易

**Comment by liuweiGL** [comment]
目前使用 ArrayList 还是停卡的，5 行 * 13 列大概需要四五秒。

**Comment by sep2** [comment]
对比一下 react-hook-form 有什么优缺点？

**Comment by yuyiRai** [comment]
列表的渲染性能更多感觉还是react自身的问题，建议直接使用mobx/mobx-react

**Comment by janryWang** [comment]
Formily2.x已经完全重构
