### ISSUE TITLE
字段解构功能希望额外添加一个属性，而不是使用 name。

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/formily#1057]
## 目前存在的问题
解构功能与 `x-linkages` 组合在一起不易维护：
1. 如果解构的字段比较多，代码太难看
2. 因为是字符串，多个空格少个空格都很难检测
3. 解构的字段跟 `x-linkages` 强关联了，修改一处，有关联的地方都要跟着改动
![image](https://user-images.githubusercontent.com/21048878/97948285-0dade980-1dcb-11eb-8cf6-19137efe11bd.png)

## 希望的特性
添加一个额外的 `mapping` 字段，专门用来存解构信息：
![image](https://user-images.githubusercontent.com/21048878/97948524-cd02a000-1dcb-11eb-8a7a-8beedf5dad85.png)

**Comment by janryWang** [comment]
2.x中的schema协议改为x-reactions被动联动模式了，可以大大减少代码量

**Comment by liuweiGL** [comment]
2.0 版本并没有解决该问题，`name` 属性跟结构功能放在一起还是会导致代码很难维护，因为 `name` 是会被 `effects` 跟 `reactions` 作为标识引用的。

**Comment by janryWang** [comment]
不可能单独用一个属性的，因为数据的读写都是基于name的，还有，你都用2.0了，为啥还要用target，你直接在被联动的字段上配置x-reactions不就行了

**Comment by liuweiGL** [comment]
1. 如果联动的两个字段都使用解构功能，不管是主动还是被动联动都是一样的问题啊，总归要把解构的字符串当做唯一标识。
2. 还有就是在 effects 中太难用了。

**Comment by janryWang** [comment]
你的应用实际痛点是什么，难道全是解构用法？一般情况下，我们都是推荐直接自定义组件内部就消化掉这种问题的，比如在Void自定义组件内部直接用Field，联动用useFormEffects，解构场景主要是用在第三方组件与后端数据不兼容，能用到解构的通常都是在比较恶心的场景会用到，如果你把解构作为标准方案，那就是你业务逻辑设计的问题了

**Comment by janryWang** [comment]
解构的定位就是为了解决恶心问题，但是它不是银弹，也不是推荐到处都用解构的，它的副作用就是你说的写法太繁杂
