### ISSUE TITLE
自增列表提供了initialValues的时候，删除一项，再添加一项，新增会默认展示旧数据的行为可以配置吗

### ISSUE THREAD

**Issue by asevenm** [alibaba/formily#1058]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
自增列表的initialValues只作为默认的展示，与后续用户的增删
**Describe alternatives you've considered**

**Additional context**
业务场景：编辑含有自增列表的表单时，由于提供了initialValues，会出现上述问题，当列表项存在很多表单配置的时候，就显得很麻烦了

**Comment by janryWang** [comment]
可以把initialValues改为value
