### ISSUE TITLE
ArrayList 使用 onFieldInputChange 之后删除/上下移操作会导致 Item 项 enum 数据显示异常

### ISSUE THREAD

**Issue by wiolem** [alibaba/formily#1061]
**Describe the bug**

复现步骤：行业 店铺 select 都选择

1. add One
2. add Two
3. remove One
4. add Three
5. add Four
6. remove Two

此时店铺 Four 的 enum 会变成 刚删除的 店铺 Two 的 enum，导致匹配异常

**To Reproduce**

https://codesandbox.io/s/happy-khayyam-mnbm7?file=/index.js

**Comment by janryWang** [comment]
2.x中借助mobx已经从根本上解决了状态交换的问题，1.x在状态交换上的设计始终有缺陷
