### ISSUE TITLE
renderRemove 自定义按钮点击不生效

### ISSUE THREAD

**Issue by zhangxiangqiang** [alibaba/formily#1067]
**Describe the bug**

自增列表里，自定义删除按钮， 这样写点击不生效

```
 x-component-props={{
            renderRemove: ()=>'remove',  // 删除点击无反应
            renderAddition: () => '+add',   // 添加可以生效
          }}

```
**To Reproduce**
Please using Codesandbox
- [@formily/next bug report template](https://codesandbox.io/s/boring-dawn-tixps)
- [@formily/antd bug report template](https://codesandbox.io/s/lively-sky-pf5c3)

**Expected behavior**
希望可以正常删除

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac
 - Browser [e.g. chrome, safari] chrome

版本信息：
"@formily/antd": "^1.3.8",
 "@formily/antd-components": "^1.3.8",

**Smartphone (please complete the following information):**

**Additional context**

**Comment by janryWang** [comment]
如果传的函数，则必须返回一个ValidElement，因为组件会往Element传onClick事件
