### ISSUE TITLE
x-rules=url，正则校验期望域名能加入下划线“_”

### ISSUE THREAD

**Issue by dk-plus** [alibaba/formily#1077]
当x-rules=url时，域名存在下划线_导致url校验不通过，比如https://asd_asd.asd_asd.com，希望官方能支持这个。

自己自定义正则也可以，但还是希望官方做合理一点，假设这种情况是存在的，那每个接入formily的项目都要重新定义url，这个预设的url就没意义了

**Comment by janryWang** [comment]
2.x中已经支持
