### ISSUE TITLE
使用ArrayTable的时候，设置两个initialValues(或者defaultValue),删除第一个，进行reset操作会有重复数据进行reset操作会有重复数据,点击下面+也会有数据重复，全部删除之后新增还是会有数据

### ISSUE THREAD

**Issue by dyw823** [alibaba/formily#1078]
**Describe the bug**
使用ArrayTable的时候，设置两个initialValues(或者defaultValue),删除第一个，进行reset操作会有重复数据,点击下面+也会有数据重复，全部删除之后新增还是会有数据，效果如下：
![image](https://user-images.githubusercontent.com/29854317/101125411-23b20280-3634-11eb-8188-04cd77a3bef4.png)
![image](https://user-images.githubusercontent.com/29854317/101125419-2b71a700-3634-11eb-9d54-a53fe1fd444c.png)

**To Reproduce**
https://codesandbox.io/s/muddy-firefly-55onv?file=/src/App.js:757-770

**Comment by janryWang** [comment]
把initialValues改为value即可
