### ISSUE TITLE
composition 被打断的情况

### ISSUE THREAD

**Issue by uinz** [alibaba/formily#1088]
合成输入被打断

简单看来是 Feild 组件必须作为直接 children 放在 Form 里, 否则就为出现 composition 被打断的情况

## codesandbox

下面这个是我拿官方的例子放到 codesandbox 上跑的效果
https://codesandbox.io/s/icy-snow-yhwwo?file=/src/App.js

![屏幕录制2020-12-13 下午4 26 47](https://user-images.githubusercontent.com/12208108/102007045-99b71780-3d60-11eb-82c1-4fe93b5d3f49.gif)

**Desktop (please complete the following information):**
 - OS: Mac Big Sur 11.0.1 (20B50)
 - Browser Chrome 87.0.4280.88

**Comment by janryWang** [comment]
这个问题在StrictMode下会存在，在2.x中会解决
