### ISSUE TITLE
不做个可视化的编辑器么？

### ISSUE THREAD

**Issue by chenzhenyang** [alibaba/formily#1090]
不做个可视化的编辑器么？

**Comment by chenz24** [comment]
我正在做，公司项目。希望将来可以开源

https://user-images.githubusercontent.com/4099122/104795482-adcfb800-57e9-11eb-8283-425df028bb77.mp4

**Comment by udbmnm** [comment]
已经有了
https://form-render.github.io/schema-generator/_demos/formily-pg

**Comment by dengxianMo** [comment]
> 已经有了
> https://x-render.gitee.io/schema-generator/

这个是form-render的吧，不是formily的

**Comment by udbmnm** [comment]
> > 已经有了
> > https://x-render.gitee.io/schema-generator/
> 
> 这个是form-render的吧，不是formily的

https://x-render.gitee.io/schema-generator/_demos/formily-pg

**Comment by Nokecy** [comment]
大佬们 2.0的可视化编辑器有吗~~

**Comment by janryWang** [comment]
> 大佬们 2.0的可视化编辑器有吗~~

等正式版发布会有的

**Comment by Nokecy** [comment]
期待~ 正式版要到2021年年底吧，会不会先放个测试版出来的出来

**Comment by janryWang** [comment]
> 期待~ 正式版要到2021年年底吧，会不会先放个测试版出来的出来

正式版发布，才出编辑器的测试版...节奏是这样的

**Comment by F-loat** [comment]
> > > 已经有了
> > > https://x-render.gitee.io/schema-generator/
> > 
> > 
> > 这个是form-render的吧，不是formily的
> 
> https://x-render.gitee.io/schema-generator/_demos/formily-pg

地址更新 https://x-render.gitee.io/tools/generator/playground?type=formily

**Comment by dingyanqiang** [comment]
打算用这套方案开发项目，希望基于可视化编辑器；但是现在formily V2的可视化编辑器还没有；V1版本又马上被V2替换，好纠结。

**Comment by 95Key** [comment]
请问后续的可视化编辑器是打算使用 https://x-render.gitee.io 还是 https://github.com/alibaba/designable ？还是期望可视化编辑器配合使用 谢谢！

**Comment by janryWang** [comment]
> 请问后续的可视化编辑器是打算使用 https://x-render.gitee.io 还是 https://github.com/alibaba/designable ？还是期望可视化编辑器配合使用 谢谢！

基于designable

**Comment by 95Key** [comment]
> > 请问后续的可视化编辑器是打算使用 https://x-render.gitee.io 还是 https://github.com/alibaba/designable ？还是期望可视化编辑器配合使用 谢谢！
> 
> 基于designable

👍  看了一下交互挺舒服的，期待早日完善上线！感谢

**Comment by isunkui** [comment]
> > > > 已经有了
> > > > https://x-render.gitee.io/schema-generator/
> > > 
> > > 
> > > 这个是form-render的吧，不是formily的
> > 
> > 
> > https://x-render.gitee.io/schema-generator/_demos/formily-pg
> 
> 地址更新 https://x-render.gitee.io/tools/generator/playground?type=formily

这个地址好像失效了。

**Comment by janryWang** [comment]
@isunkui http://designable-antd.formilyjs.org/

**Comment by Turkyden** [comment]
@janryWang x-render 和 formily 最大的区别是什么呢？有对比么？该怎么选？

**Comment by janryWang** [comment]
> @janryWang x-render 和 formily 最大的区别是什么呢？有对比么？该怎么选？

https://github.com/alibaba/formily/discussions/1561

**Comment by lovewinders** [comment]
目前正在技术选型，期待formily官方2.0表单设计器早日出现

**Comment by cheneywan** [comment]
> @isunkui 不用看x-render了，formily官方2.0表单设计器地址：https://designable-antd.formilyjs.org/ 目前正在开发中，预计8月中旬可用

不知道这个 Demo 也会完整的开源么？包括右侧的组件和左侧表单数据源配置等等
目前 https://github.com/alibaba/designable 这里面比较缺乏文档
@janryWang

**Comment by zuosamu** [comment]
> > @isunkui 不用看x-render了，formily官方2.0表单设计器地址：https://designable-antd.formilyjs.org/ 目前正在开发中，预计8月中旬可用
> 
> 不知道这个 Demo 也会完整的开源么？包括右侧的组件和左侧表单数据源配置等等
> 目前 https://github.com/alibaba/designable 这里面比较缺乏文档
> @janryWang

期待ing

**Comment by janryWang** [comment]
已经支持

**Comment by kakarot1874** [comment]
> > 大佬们 2.0的可视化编辑器有吗~~
> 
> 等正式版发布会有的

编辑器不开源吗 https://designable-antd.formilyjs.org/
