### ISSUE TITLE
相同name组件，其他属性不同，渲染bug

### ISSUE THREAD

**Issue by hashplus** [alibaba/formily#1092]
**Describe the bug**
相同name组件，其他属性不同，渲染bug

**To Reproduce**
Please using Codesandbox
- [复现](https://codesandbox.io/s/old-brook-jedi8?file=/index.js)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by janryWang** [comment]
并没有复现问题

**Comment by hashplus** [comment]
![image](https://user-images.githubusercontent.com/2285017/104086089-9d6e8900-528f-11eb-8ac3-d772bff19973.png)
相同name的控件`placeholder`不同，页面渲染成相同`placeholder`

**Comment by janryWang** [comment]
> ![image](https://user-images.githubusercontent.com/2285017/104086089-9d6e8900-528f-11eb-8ac3-d772bff19973.png)
> 相同name的控件`placeholder`不同，页面渲染成相同`placeholder`

目前是不支持管理相同name的状态
