### ISSUE TITLE
object is not extensible

### ISSUE THREAD

**Issue by Gamehu** [alibaba/formily#1096]
**Describe the bug**
Uncaught TypeError: Cannot add property Symbol(@@__YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG__@@), object is not extensible http://localhost:3333/js/index.js 271046 7 TypeError: Cannot add property Symbol(@@__YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG__@@), object is not extensible

**To Reproduce**
 
- [demo](https://codesandbox.io/s/tablefield-zuiv7?file=/index2.js:5511-5607)

**Expected behavior**

 
 

**Additional context**
 
链接里使用没问题，但是结合ice.js使用，则报错：

Uncaught TypeError: Cannot add property Symbol(@@__YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG__@@), object is not extensible http://localhost:3333/js/index.js 271046 7 TypeError: Cannot add property Symbol(@@__YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG__@@), object is not extensible

**Comment by KellenHe** [comment]
@Gamehu 请问这个问题是怎么解决的？ 我也遇到了
