### ISSUE TITLE
formily 引入 hoist-non-react-statics 引起 antd@3.x 下初始化报错

### ISSUE THREAD

**Issue by postbird** [alibaba/formily#1133]
**Describe the bug**

`antd-components` 下 `time-picker` 增加了 `RangePicker`，antd@3.x 下没有这个组件， connect 时候，connect 了 undefined（[代码](https://github.com/alibaba/formily/blob/master/packages/antd-components/src/time-picker/index.tsx#L48)）

引入 `hoist-non-react-statics` 后，因为 undefined 在初始化时报错

![image](https://user-images.githubusercontent.com/16200574/106101163-74e3fb80-6178-11eb-8bd5-d59dfcef1b9f.png)

**To Reproduce**

https://codesandbox.io/s/nervous-rosalind-277ng?file=/src/App.js

**Comment by vincenthou** [comment]
Come across with the same issue

**Comment by janryWang** [comment]
先锁死版本号吧，下个版本我加个容错

**Comment by laughing-pic-zhu** [comment]
+1

**Comment by Benait7** [comment]
这个问题困扰我了半天。。。。

**Comment by janryWang** [comment]
已修复，升级最新版即可
