### ISSUE TITLE
submit loading 无效

### ISSUE THREAD

**Issue by kotot** [alibaba/formily#1135]
**Describe the bug**

**To Reproduce**
Please using Codesandbox
- [@formily/next bug report template](https://codesandbox.io/s/boring-dawn-tixps)
- [@formily/antd bug report template](https://codesandbox.io/s/lively-sky-pf5c3)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://codesandbox.io/s/icy-tree-z8rdn?file=/index.js

**Comment by janryWang** [comment]
Submit组件不需要手动设置loading，在onSubmit函数中返回promise对象，它会自动显示loading的

**Comment by kotot** [comment]
> Submit组件不需要手动设置loading，在onSubmit函数中返回promise对象，它会自动显示loading的

确实可以，但是文档里面的描述会让人误解，最好注释一下

**Comment by kotot** [comment]
https://github.com/alibaba/formily/blob/f478fb329bbf807305131fac200056539fa21d43/packages/next/src/components/Button.tsx#L44
看了下 源码，submit的loading就是个迷惑选项吧，完全没用
