### ISSUE TITLE
SchemaField path 渲染带值问题

### ISSUE THREAD

**Issue by shanliang** [alibaba/formily#1137]
`{toArr(value).map((item, index) => {
        return (
          <RowStyleLayout {...componentProps} key={index}>
            <span>#{index + 1}. </span>
            <SchemaField path={FormPath.parse(path).concat(index)} />
            <Field name="username" x-component="Input" title="用户名" />
            <Field name="age" x-component="Input" title="年龄" />`
上面是官网上自增列表组件代码片段，请问
如何让<SchemaField path={FormPath.parse(path).concat(index)} />渲染出来的组件带上 item 上的值。
不然 每次 重新渲染 上次输入的值会丢失

**Comment by janryWang** [comment]
给Form传initialValues就能带上默认值了
