### ISSUE TITLE
项目使用 FormMegaLayout 和 umi/qiankun 来回切换第二次子应用 FormMegaLayout样式消失

### ISSUE THREAD

**Issue by Aries296992400** [alibaba/formily#1140]
![image](https://user-images.githubusercontent.com/39082776/106714684-28e0fd00-6637-11eb-8181-659cc1dff94b.png)

![image](https://user-images.githubusercontent.com/39082776/106714731-37c7af80-6637-11eb-86c1-9f71a2cf970e.png)

**Comment by jxbb** [comment]
可能是使用 styled-components 的原因

**Comment by janryWang** [comment]
styled-component版本号不一致，会导致样式丢失，也就是不同子应用间依赖的stc版本号不同
