### ISSUE TITLE
Json schema definitions and reusability

### ISSUE THREAD

**Issue by ccpu** [alibaba/formily#1147]
**Is your feature request related to a problem? Please describe.**
Apparently  formily is not supporting [definitions & ref ](https://json-schema.org/understanding-json-schema/structuring.html#reuse), I think its very useful feature that need to be included in this library, it will simplifies reusability. 

wondering if there is  a plan to add this feature?

**Describe the solution you'd like**
To be able add definitions as follow:

```json
{
  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    },
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "title": "Billing address",
      "$ref": "#/definitions/address"
    },
    "shipping_address": {
      "title": "Shipping address",
      "$ref": "#/definitions/address"
    },
  }
}
```

**Describe alternatives you've considered**
Currently I have to check schema properties reclusively and link the references.

**Comment by janryWang** [comment]
Thank you very much for your valuable comments, we can consider adding this feature in the 2.x version

**Comment by janryWang** [comment]
Supported
