### ISSUE TITLE
JSX Schema 方式 <SchemaForm />不支持map

### ISSUE THREAD

**Issue by zhaoyanbei** [alibaba/formily#1164]
SchemaForm 内用JSX方式map Field 报类型错误;

不能将类型“{ children: (string | (() => Element[]) | Element)[]; components: { Input: MixinConnectedComponent<"TextArea">; Select: MixinConnectedComponent<"">; Checkbox: MixinConnectedComponent<...>; CheckboxGroup: FC<...>; }; onSubmit: { ...; }; }”分配给类型“ISchemaFormProps<any, any, any, ISchemaFormActions | ISchemaFormAsyncActions>”。
  属性“children”的类型不兼容。
    不能将类型“(string | (() => Element[]) | Element)[]”分配给类型“ReactElement<any, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)> | ReactElement<any, string | ((props: any) => ReactElement<...>) | (new (props: any) => Component<...>)>[] | ((form: { ...; }) => ReactElement<...>)”。
      不能将类型“(string | (() => Element[]) | Element)[]”分配给类型“ReactElement<any, string | ((props: any) => ReactElement<any, any>) | (new (props: any) => Component<any, any, any>)>[]”。

**Comment by janryWang** [comment]
给个例子看看

**Comment by zhaoyanbei** [comment]
已经解决
