### ISSUE TITLE
2.0中扩展一个组件，表单获取的值和state中获取的不一致？

### ISSUE THREAD

**Issue by wittech** [alibaba/formily#1165]
在2.0中扩展一个tree的组件，将选中的值传递给onChange事件，selectedKeys为数组类型。
export const AntdTree = connect(
observer((props: any) => {
......
const onSelect = (selectedKeys, e) => {
if (onChange) {
onChange(selectedKeys);
}
};
......
}
在表单的effects中获取：
onFormInputChange((form) => {
console.log(form.getFormState().values) //获取为：tree: ["2"]
console.log(form.values) //获取为：Proxy {Symbol(mobx administration): ObservableObjectAdministration}
});

**Comment by janryWang** [comment]
getFormState拿到的是深度clone后的数据，form.values是observable对象
