### ISSUE TITLE
isArrayList 判断导致 effects 修改值类型时 object 被强制转换为 array

### ISSUE THREAD

**Issue by muxfe** [alibaba/formily#1175]
https://github.com/alibaba/formily/blob/9db2eeb774f5678624bdc0bb626cfb38ebaab44e/packages/core/src/models/field.ts#L332

formily 底层有一个判断 array 类型的方式（根据 type 是否有 array 字符串出现）

我们有一个需求是会在 effects 里修改字段值的类型，比如 array 改为 object 类型，但是会被强制改为 array 类型

请问有什么办法避免这种强制转换吗

CodeSandbox 链接：
<https://codesandbox.io/s/reverent-bhaskara-sxzsi?file=/src/App.js>

**Comment by janryWang** [comment]
不推荐动态修改数据类型，formily需要一个稳定的数据结构
