### ISSUE TITLE
ArrayCards 中无法使用Upload组件 上传异常

### ISSUE THREAD

**Issue by majyg468** [alibaba/formily#1200]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - ArrayCards 子元素里面使用upload组件 上传报错 
  - What is the expected behavior? ArrayCards正常使用
  - Which versions of Formily? 2.0.0-beta.7

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
- 复现地址 https://codesandbox.io/s/green-resonance-6qb3p

**Comment by janryWang** [comment]
例子打不开，报错了

**Comment by majyg468** [comment]
> 例子打不开，报错了
例子里面报错
ModuleNotFoundError
Could not find module in path: 'rc-util/5.0.6/es/Dom/dynamicCSS' relative to '/node_modules/@ant-design/icons/es/utils.js'

这个是antd icons组件 里报的 里面引用的依赖没有 我这边本地没有问题  需要你们一起看看

**Comment by janryWang** [comment]
https://codesandbox.io/s/51bup 这个例子就没报错，应该是你的配置问题

**Comment by majyg468** [comment]
> https://codesandbox.io/s/51bup 这个例子就没报错，应该是你的配置问题

我刚刚试了     "@ant-design/icons": "4.4.0", 这个版本可以 4.6.2的版本有问题
你现在可以试下了  
直接上传没问题 在arraycards 里面的上传有问题

**Comment by janryWang** [comment]
已修复，2.0.0-beta.19
