### ISSUE TITLE
[V2] Is fullfill misspelled?

### ISSUE THREAD

**Issue by ccpu** [alibaba/formily#1203]
I am not English exert but i think `fullfill` should be `fulfill` with one "L", it would be better to fix it in early stage.

**Comment by janryWang** [comment]
Wow, thank you very much, I really didn’t notice this before

**Comment by janryWang** [comment]
Hi, Bro, can we add a WeChat?

**Comment by ccpu** [comment]
hi janery, unfortunately i don't use any chatting services, however I do use tweeter; here is the link if interested: [Mo_D](https://twitter.com/Mo_Do_08).

Also if you are interested have a look at spell check extensions for your editor, i myself make a lot of english mistake and extention has helped me a lot, this is how i notice the `fullfill` misspelled, [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) is what i use for vscode, it is very powerfull.

And finally i would like to thank you for such thoughtful library, its so powerful with clever design.

**Comment by janryWang** [comment]
Wow, it's cool, emm, but i want to  know. Are you Chinese? Do you understand Chinese documents?

**Comment by ccpu** [comment]
No i am iranian-british, and unfortunately i don't understand Chinese language, i use google  to translate chinease docs, and its doing a grate job of translating Chinese.

**Comment by janryWang** [comment]
Oh, I'm very sorry, if possible, I will definitely provide the English version of the document. 😭

**Comment by ccpu** [comment]
No need to be sorry, you have already done a great job providing this library,  and to be honest i haven't had any problem reading your doc in Chinese, simply right click and click translate :)

**Comment by janryWang** [comment]
Hi, @ccpu , Now, Formily entry site already have the english version document. but, I don't know if you can understand. 😂

**Comment by ccpu** [comment]
That's awesome, thank you, much appreciated.

**Comment by janryWang** [comment]
> That's awesome, thank you, much appreciated.

Here is formily twitter https://twitter.com/FormilyT, Welcome to follow.
