### ISSUE TITLE
@formily/vue使用报错

### ISSUE THREAD

**Issue by knight-peter** [alibaba/formily#1220]
**Describe the bug**
使用@formily/vue文档上的例子时报错。
```
<template>
  <FormProvider :form="form">
    <SchemaField :schema="schema" />
  </FormProvider>
</template>

<script>
  import { Input } from 'ant-design-vue'
  import { createForm } from '@formily/core'
  import { FormProvider, createSchemaField } from '@formily/vue'
  import 'ant-design-vue/dist/antd.css'

  const { SchemaField } = createSchemaField({
    components: {
      Input,
    },
  })

  export default {
    components: { FormProvider, SchemaField },
    data() {
      return {
        form: createForm(),
        schema: {
          type: 'object',
          properties: {
            input: {
              type: 'string',
              'x-component': 'Input',
              'x-component-props': {
                placeholder: '请输入',
              },
            },
          },
        },
      }
    },
  }
</script>
```
报错：
```
[Vue warn]: Error in callback for immediate watcher "function () { return props.form; }": "TypeError: target.onMount is not a function"
vue.runtime.esm.js?2b0e:1888 TypeError: target.onMount is not a function
[Vue warn]: Error in callback for immediate watcher "function () { return source.map(function (s) { return (isRef(s) ? s.value : s()); });
vue.runtime.esm.js?2b0e:1888 TypeError: formRef.value.createField is not a function
```

**Comment by janryWang** [comment]
能否给个复现地址呢

**Comment by knight-peter** [comment]
> 能否给个复现地址呢
> 
> Can you give me a forwarding address

我把相关代码放到这个仓库了`https://github.com/knight-peter/formilyVueRend.git`
路由是`/test`

**Comment by finaldusk** [comment]
> 能否给个复现地址呢

同样跑例子报错信息不同
https://codesandbox.io/s/wandering-currying-11gwt?file=/src/App.vue

**Comment by MisicDemone** [comment]
> > 能否给个复现地址呢
> 
> 同样跑例子报错信息不同
> https://codesandbox.io/s/wandering-currying-11gwt?file=/src/App.vue

这个感觉是vue-demi安装的有点问题。

vue-demi在preinstall的时候根据当前项目的vue版本决定导出的内容，默认是从vue(v3)的包里导出defineComponent，如果是vue2则是从@vue/composition-api里导出。从报错看这里应该是preinstall hook没有执行，然后就去vue的包里找了，就找不到

**Comment by finaldusk** [comment]
> > > 能否给个复现地址呢
> > 
> > 
> > 同样跑例子报错信息不同
> > https://codesandbox.io/s/wandering-currying-11gwt?file=/src/App.vue
> 
> 这个感觉是vue-demi安装的有点问题。
> 
> vue-demi在preinstall的时候根据当前项目的vue版本决定导出的内容，默认是从vue(v3)的包里导出defineComponent，如果是vue2则是从@vue/composition-api里导出。从报错看这里应该是preinstall hook没有执行，然后就去vue的包里找了，就找不到

感谢，我的项目是Vue2但是vue-demi 判断当前版本为Vue3 执行npx vue-demi-fix后问题解决
