### ISSUE TITLE
点击表单提交导致浏览器崩溃

### ISSUE THREAD

**Issue by li9269391** [alibaba/formily#1255]
**Describe the bug**
1、官网例子中，如果没有在输入框填写内容，而是直接点 submit 提交，浏览器崩溃。
2、在本地表现，去掉设置 validateFirst: true，正常
3、在本地 umi 中表现正常

**To Reproduce**
Please using Codesandbox
- [来自官网例子](https://codesandbox.io/s/n7kbb)

**Expected behavior**
可以正常校验或提交

**Screenshots**
![image](https://user-images.githubusercontent.com/10287877/115328244-df7a6580-a1c2-11eb-8cc1-6ff1b6076cc4.png)
![image](https://user-images.githubusercontent.com/10287877/115328261-e73a0a00-a1c2-11eb-843d-7aed9a71a652.png)

**Desktop (please complete the following information):**
 - macOS v10.15.6
 - chrome v89.0

**Comment by janryWang** [comment]
并不是崩溃，codesandbox catch了unhandlereject。这是submit提交校验失败会走到reject中

**Comment by li9269391** [comment]
好的，但我在本地开发是表现没响应，页面卡住无法操作，codesandbox重现不出

**Comment by li9269391** [comment]
或者说如何捕捉catch，怎么写有示例吗，使用的是schema form，似乎也找不到 reset 表单的示例

**Comment by janryWang** [comment]
1.x的看1.x的文档，不要看错

**Comment by li9269391** [comment]
> 1.x的看1.x的文档，不要看错

你好，确认是2.x的，submit要什么要注意的吗。就是在本地，https://codesandbox.io/s/8z7he，照着这个实现，点提交就卡住，只能强制关掉浏览器选项卡，也没有提示

**Comment by li9269391** [comment]
我先换个干净的项目试试

**Comment by li9269391** [comment]
@janryWang 我这边提交了一份[可重现问题的demo](https://github.com/li9269391/formily-learn-demo)。
另补充说明：在此demo中，我加入 React.StrictMode 就能重现。但感觉并不是 StrictMode 的问题，因为尝试在 create-react-app 中尝试加入 StrictMode又是正常，所以这个问题困惑了很久，可否帮忙看看是什么原因导致，多谢

**Comment by janryWang** [comment]
codesandbox没法复现，https://codesandbox.io/s/quirky-pasteur-trxqf?file=/index.tsx

**Comment by li9269391** [comment]
> codesandbox没法复现，https://codesandbox.io/s/quirky-pasteur-trxqf?file=/index.tsx

建议本地跑一下试试

**Comment by li9269391** [comment]
觉得大部分项目还没有用上 umi 或  create-react-app，自配置 webpack 比较多，所以这个问题感觉必现，大佬可否看看呢？

**Comment by li9269391** [comment]
升级 2.0.0-beta.42 后已解决！
