### ISSUE TITLE
the `registerValidateLocale` did not work properly in the doc example of V2

### ISSUE THREAD

**Issue by smalldragonluo** [alibaba/formily#1256]
**Describe the bug**
the `registerValidateLocale` did not work properly in the doc example of V2

**Screenshots**
![image](https://user-images.githubusercontent.com/7576698/115333752-cb3b6600-a1cc-11eb-9956-aa157d851827.png)

**Comment by janryWang** [comment]
please give me a codesandbox to reproduce this case

**Comment by janryWang** [comment]
This problem is because the internal browser language identifier is zh-CN, but the registered one is zh, so it will not match. Just add a setValidateLangugage("zh")
