### ISSUE TITLE
Issue with displaying file list using Drag & Drop upload (使用拖拽上传的文件列表显示有问题)

### ISSUE THREAD

**Issue by cning112** [alibaba/formily#1269]
**Describe the bug**
File list display area is covered by form buttons

**To Reproduce**
use "拖拽上传" in https://antd.formilyjs.org/components/upload. File list display area will be covered by other elements

**Expected behavior**
The file list display using drag&drop upload should be the same as using normal/card upload

**Screenshots**
![image](https://user-images.githubusercontent.com/1435934/115592605-569b2100-a2cb-11eb-96cd-c78751347cf3.png)

**Comment by janryWang** [comment]
Fixed
