### ISSUE TITLE
Npm latest code seems like not sync with github?

### ISSUE THREAD

**Issue by programmerwy** [alibaba/formily#1278]
npm: @formily/react@2.0.0-beta.33
github: master

Background: I try to use `createSchemaField` to add `scope`, so that I can use `{{fetch}}` in `Select` to get data dynamically. Before that , I want to read the source code on github, but not found, the code is on the npm only

**Comment by janryWang** [comment]
check this branch
https://github.com/alibaba/formily/tree/formily_next
