### ISSUE TITLE
2.0.0-beta.36 版本中的 Schema.registerTypeDefaultComponents 不生效

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/formily#1307]
**Describe the bug**
从 2.0.0-beta.35 升级到 2.0.0-beta.36 之后 `Schema.registerTypeDefaultComponents` 注册的组件不生效了。

**想法**
看了源码发现 `registerTypeDefaultComponents` 跟 `SpecificationV1Polyfill` 绑定在一起了，需要使用 `enablePolyfills` 开启才会生效。 有个困惑就是 `enablePolyfills` 是带版本概念的， 那么 `registerTypeDefaultComponents` 是否也应该引入版本的概念呢？

**其他**
`registerTypeDefaultComponents`  api 文档可能需要指明和 `enablePolyfills` 配合使用。

**Comment by janryWang** [comment]
说的对，欢迎提个PR，帮忙给文档加一下提醒吧

**Comment by liuweiGL** [comment]
好的，晚一点点。
