### ISSUE TITLE
JSON Schema 异步联动数据源案例，渲染失败，死循环

### ISSUE THREAD

**Issue by galaa2011** [alibaba/formily#1318]
![image](https://user-images.githubusercontent.com/6466472/116246565-b0ed2380-a79c-11eb-85a0-5f4f73396fed.png)
![image](https://user-images.githubusercontent.com/6466472/116246804-ded26800-a79c-11eb-94bb-5b99bb930842.png)

- mac 
- chrome

[官网案例](https://antd.formilyjs.org/components/select)，死循环报错。求解？

**Comment by janryWang** [comment]
没法复现呀

**Comment by galaa2011** [comment]
> 没法复现呀

![image](https://user-images.githubusercontent.com/6466472/116252569-45a65000-a7a2-11eb-9a92-d201f24b2f85.png)

试试这个严格模式

**Comment by janryWang** [comment]
already fixed

**Comment by galaa2011** [comment]
2.x的版本没有开源吗，看不到你的修复记录。想了解下是怎么处理的

**Comment by galaa2011** [comment]
试了下beta.40的版本，好像还不行呢？
https://codesandbox.io/s/solitary-architecture-4393t?file=/index.tsx

**Comment by janryWang** [comment]
的确还没解决，我再详细看看

**Comment by janryWang** [comment]
这次解决了，主要问题就是更新队列管理的问题
