### ISSUE TITLE
input 表单值为空默认会取 schema default 值

### ISSUE THREAD

**Issue by jiangxinlei** [alibaba/formily#1321]
问题描述：
input 表单值为空字符串时，表单内的值默认会取 schema default 属性值，所以会导致每次清空 input 值，再刷新，表单内会一直不变。

预览图：
![image](https://user-images.githubusercontent.com/29573321/116371946-88b60100-a83e-11eb-9600-e67ddfb9b670.png)

案例：https://codesandbox.io/s/amazing-field-pxgm6?file=/index.js

期望结果：
值为空时，表单展示也是空，不要取 schema default 值

**Comment by janryWang** [comment]
这个问题是一直存在的问题，涉及到内核改动，主要是默认值合并策略上存在设计上的缺陷，如果要改造，影响非常大，建议升级v2，或者在现有版本上不要传空字符串，改成传"NONE"或者手动setFieldState去清空value
