### ISSUE TITLE
[formily2.0]@formily/shared包中是否可以将@formily/react的依赖去掉

### ISSUE THREAD

**Issue by hugo429586472** [alibaba/formily#1332]
**描述**
目前@formily/vue包会依赖于@formily/shared包，而@formily/shared里的package.json会引入@formily/react的依赖。
@formily/shared包中使用react包相关文件：checker.ts、package.json

**建议**
目前这样会导致在用@formily/vue时会引入react相关的所有包，希望是shared包保持独立性移除对@formily/react的依赖，与具体使用的js框架无关。

**其他**
1.@formily/vue包中types/index.ts文件也包含了对react的引用，希望也能去掉。
2.@formily/vue包内部是同时支持vue2和vue3的，不过在包内部引入处理时，vue3是通过import('vue3')进行处理、vue2是import from 'vue'进行处理，在vue3项目中使用时这块会有问题（全局vue包是3.0版本的，而且没有vue3这个包）。希望是能进行调整的，或者提供在引入的项目如何处理的文档。

**Comment by janryWang** [comment]
@MisicDemone 我来看看shared包的依赖去除，你看看第二个问题吧

**Comment by janryWang** [comment]
我看了下shared包，其实就只是依赖了@types/react，并没有在实际打包的时候影响到@formily/vue的体积的

**Comment by hugo429586472** [comment]
我看了下我这边打包输出，打包时应该是不会将@types/react打包进去，不过因为shared包checker.ts中有使用到这个react的包（React.ReactElement），导致引入的时候会要求依赖于@types/react（在引入的checker.ts中会包含/// <reference types="react" />）。
而实际打包时是没有将@types/react打包进去的，打包就会报错（Cannot find type definition file for 'react'和Cannot find module 'react'）。

**Comment by MisicDemone** [comment]
vue 类型问题已修复: [https://github.com/alibaba/formily/pull/1433](https://github.com/alibaba/formily/pull/1433)
