### ISSUE TITLE
formily 2.0 array-table 如果列很多 横向滚动条位置错误

### ISSUE THREAD

**Issue by Nokecy** [alibaba/formily#1341]
https://codesandbox.io/s/cranky-browser-iwyyg?file=/App.tsx

横向滚动条出现在页面底部

**Comment by janryWang** [comment]
Fixed

**Comment by Nokecy** [comment]
@janryWang  好像还没玩完全解决~~ 当用FormItem包裹ArrayTable并使用 labelCol 属性时，页面底部还是会出现滚动条
https://codesandbox.io/s/intelligent-voice-qcr38?file=/App.tsx

**Comment by janryWang** [comment]
用法不规范，不能只配labelCol，wrapperCol也要配

**Comment by Nokecy** [comment]
~~~了解
