### ISSUE TITLE
[Formily JSON Schema]: Cannot find the 'Editable.Popover' component mapped by Schema.x-component 

### ISSUE THREAD

**Issue by XuFeng-Li** [alibaba/formily#1342]
@formily ^2.0.0-beta.41
https://antd.formilyjs.org/components/editable   例子中的源码复制

  dependencies:

    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@formily/antd": "^2.0.0-beta.42",
    "@formily/core": "^2.0.0-beta.42",
    "@formily/react": "^2.0.0-beta.42",
    "typescript": "^4.1.2"

报错：
[Formily JSON Schema]: Cannot find the 'Editable' component mapped by Schema.x-decorator
[Formily JSON Schema]: Cannot find the 'Editable.Popover' component mapped by Schema.x-component

**Comment by janryWang** [comment]
复现不了 https://codesandbox.io/s/2z95m?file=/App.tsx

**Comment by XuFeng-Li** [comment]
对 formily 引入按需打包后的冲突？我排查了一下，我引入按需导入后就出现这个问题了
https://gitee.com/1125105110/fissue-demo.git
如果是我引入按需打包的配置有问题，烦请告知，谢谢了

**Comment by janryWang** [comment]
试试在codesandbox里加上 config-overrides.js？codesandbox也是走的create react app

**Comment by XuFeng-Li** [comment]
请问 如何让 codesandbox  走 react-app-rewired start？

**Comment by XuFeng-Li** [comment]
老哥，在 codesandbox里加上 config-overrides.js似乎没用，codesandbox不会走package.json 的 start（即：react-app-rewired start），直接执行的是 react-scripts start，所以在codesandbox里面运行正常，但是down下来，使用编译器执行会报错的
https://codesandbox.io/live/cz1lr7f

**Comment by janryWang** [comment]
我有空看一下这个问题吧，或者你也帮忙排查一下，我猜是哪个地方重复打包了
