### ISSUE TITLE
默认值为空字符串时不生效

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/formily#1358]
**问题**
`default` 设置为空字符串 `''` 时不生效。

**复现**

https://codesandbox.io/s/charming-glitter-jut1f?file=/App.tsx

期待默认选中 `全部`：
![image](https://user-images.githubusercontent.com/21048878/117521674-93f8f180-afe1-11eb-88fb-bbd1f89d7cdb.png)

**Comment by janryWang** [comment]
Fixed

**Comment by liuweiGL** [comment]
更新到 beta47 版本，这个问题还是存在呢。
