### ISSUE TITLE
使用ISchema定义报错

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [alibaba/formily#1414]
**问题**
使用ISchema定义报错。
为什么key和name要传，但是类型却没有呢？
![image](https://user-images.githubusercontent.com/60122207/118088123-2b52b000-b3f9-11eb-8cd2-e876dec2b9ad.png)

**复现**
`import { ISchema } from '@formily/antd'
export const schema: ISchema = {
  type: 'object',
  properties: {
    GENDER: {
      key: 'GENDER',
      name: 'GENDER',
      type: 'string',
      "x-component": 'select',
      enum: [],
    },
  },
}
`

**Comment by janryWang** [comment]
key不需要传的
