### ISSUE TITLE
在使用 antd4 时, 校验错误输入正确信息后, description 内容也显示为红色

### ISSUE THREAD

**Issue by xu3927** [alibaba/formily#1419]
**问题**

在 antd4 时, description 信息也显示为红色

![image](https://user-images.githubusercontent.com/18064467/118125454-93b98580-b429-11eb-96c9-209e77718efc.png)

**复现**
复现步骤:
1. 点击提交, 会显示红色的错误提示
2. 输入字符,  描述也显示为红色

请用codesandbox提供复现地址
https://codesandbox.io/s/serene-austin-1m1nn?file=/src/App.tsx

**Comment by janryWang** [comment]
antd4的bug，受控更新help和validateStatus没法恢复，对方一直没修
