### ISSUE TITLE
自定义组件onChange后不触发重渲染

### ISSUE THREAD

**Issue by wangxiaofeid** [alibaba/formily#1428]
**问题**
自定义的一个复杂输入组件，两次onChange只触发一次重渲染；
eg1: 我的组件值是数组类型[{a: 'a', b: 'b'}]，如果Field上没加type="array"，内部触发onChange不会导致重渲染
eg2: 组件值是对象且内部有存在数组{a: 'a', b: 'b', c: [{a: 'a', b: 'b'}]}，内部数组更新不会触发重渲染
**复现**
https://codesandbox.io/s/zidingyifuzashuruzujian2-639t6
**建议**
能否有配置用来标识当前组件是有onChange就需要重渲染

请用codesandbox提供复现地址

**Comment by janryWang** [comment]
1.x的设计缺陷，而且是改不了的，建议升级2.x
