### ISSUE TITLE
[Bug Report] x-reactions did't work after switch fields order

### ISSUE THREAD

**Issue by yiyijia** [alibaba/formily#1494]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-platform-svxqc?file=/App.tsx)

### Steps to reproduce
case1: order [source field   depSource field ] , result: worked
case2: order [ depSource field, source field  ],  result: didn't work as expected

### What is expected?
switch fields order should not breaks x-reactions

### Package
@formily/reactive@2.0.0-beta.56

---

**Comment by janryWang** [comment]
already fixed
