### ISSUE TITLE
[Bug Report] 使用阅读态组件时x-component-props类型报错

### ISSUE THREAD

**Issue by aspirantzhang** [alibaba/formily#1506]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-http-zn607?file=/App.tsx:778-811)

### Steps to reproduce
官网代码即可重现 https://antd.formilyjs.org/components/preview-text

### What is expected?
解决TS类型报错

### What is actually happening?
![QQ截图20210525193529.jpg](https://i.loli.net/2021/05/25/X8HmNxySjt2DKOC.jpg)

### Package
@formily/antd@2.0.0-beta.56

---

**Comment by liuweiGL** [comment]
## 问题1

`createSchemaField` 方法接收 PreviewText 时报错。

## 原因

`createSchemaField` 方法的 components 期待的是一个 Record<string, JSXComponent>，但是 PreviewText 是一个 object。

## 需明确

这个问题应该属于 `createSchemaField` 参数的类型定义错误还是使用方式错误？

**Comment by liuweiGL** [comment]
## 问题2

`x-component-props` 报错。

## 原因

这个应该是 SchemaField 类型推断有点问题，需要再看看。

**Comment by liuweiGL** [comment]
> ## 问题1
> `createSchemaField` 方法接收 PreviewText 时报错。
> 
> ## 原因
> `createSchemaField` 方法的 components 期待的是一个 Record<string, JSXComponent>，但是 PreviewText 是一个 object。
> 
> ## 需明确
> 这个问题应该属于 `createSchemaField` 参数的类型定义错误还是使用方式错误？

我觉得这个应该算使用方法错误，不然的话类型推导没法做。

**Comment by janryWang** [comment]
我感觉也是用法问题，为啥会单纯只用PreviewText。。。想不通

**Comment by liuweiGL** [comment]
不是用户的用法有问题，是组件的设计有问题：
1. PreviewText 设计成 object，导致 createSchemaField 接口类型不匹配。
2. 如果使用
```ts
const SchemaField = createSchemaField({
  components: {
    FormItem,
    "PreviewText.Input":PreviewText.Input,
  },
})
```
这个方式，x-component-props 推导出来的类型是错误的 #1507
