### ISSUE TITLE
[Bug Report] Array Field 在 FormLayout 中无法正确赋值和取值？

### ISSUE THREAD

**Issue by pandazki** [alibaba/formily#1533]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-leaf-cb4en?file=/App.tsx)

### Steps to reproduce
将任意 Array Field 放在 FormLayout，修改之后在 submit 中获取表单值。

### What is expected?
数据正确

### What is actually happening?
数组长度正确，但是值为空

![](https://user-images.githubusercontent.com/754493/120287858-39a63480-c2f2-11eb-90c2-3e4390351554.png)

### Package
@formily/antd@2.0.0-beta.59

---

**Comment by janryWang** [comment]
之前修了https://github.com/alibaba/formily/issues/1524 这个问题，没验证全面，看来这部分逻辑是真的有点复杂，得写个单测覆盖全面才行

**Comment by janryWang** [comment]
已经修复了，等下个版本
