### ISSUE TITLE
 场景案例文案错误

### ISSUE THREAD

**Issue by wegi8** [alibaba/formily#1562]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
非功能错误，只是文档错误，场景案例，登录注册，而非登陆注册，这是个细节，我自己也经常有这个错误，作为国内大厂开源的东西，显得很不在意这个库

### What does the proposed API look like?
场景案例，登陆注册=>登录注册

**Comment by janryWang** [comment]
这种typo问题推荐用户直接PR修改
