### ISSUE TITLE
[Feature Request] 有没有表单生命周期详细介绍？

### ISSUE THREAD

**Issue by LouisaNikita** [alibaba/formily#1573]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前表单生命周期是一个黑盒，不太清楚生命周期内是如何运作的

### What does the proposed API look like?
期待有一个生命周期介绍，每个节点都做了什么

**Comment by janryWang** [comment]
提问到discussion里提，还有核心文档请到子站里找
