### ISSUE TITLE
[Bug Report] 数组类型字段默认值为 [0] 时不生效

### ISSUE THREAD

**Issue by MisicDemone** [alibaba/formily#1581]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-hugle-fchv5?file=/App.tsx)

### Steps to reproduce
设置schema的default属性为[0]

### What is expected?
表单组件能回显默认值

### What is actually happening?
表单组件不能回显默认值

### Package
@formily/antd@2.0.0-beta.65

---

只有默认值为 [0] 是不能回显，为 [1] 或 [0, 1] 等均无此问题

**Comment by janryWang** [comment]
Fixed
