### ISSUE TITLE
[Bug Report] formily-vue 双向绑定约定不支持input

### ISSUE THREAD

**Issue by muuyao** [alibaba/formily#1583]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-paper-ylz2x?file=/src/App.vue)

### Steps to reproduce
input输入无反应

### What is expected?
input输入显示

### What is actually happening?
input输入无反应

### Package
@formily/vue@2.0.0-beta.65

---

el-input是基于value和input事件来实现双向绑定，formily-vue里reactive-field 目前默认绑定change，应添加input支持

**Comment by qq1037305420** [comment]
设计如此

**Comment by MisicDemone** [comment]
输入接口为value属性，输出接口为change事件是formily的接口定义。如果要接入的组件符合这套定义即可直接接入，不符合这套定义自然就需要付出一定的接入成本。以el-input为例：

``` javascript
const transformComponentEvents = (component, map) => {
  return {
    functional: true,
    render(h, context) {
      const data = context.data;
      const keys = Object.keys(map);
      keys.forEach(extract => {
        if (data.on !== undefined) {
          data.on[map[extract]] = context.listeners[extract];
        }
      });
      return h(component, data, context.children);
    }
  };
};

const Input = transformComponentEvents('el-input', { change: 'input' });
```

这套逻辑应该是存在于组件库适配层，而不应内置于formily-vue

**Comment by MisicDemone** [comment]
另外 element 接入可以参考开发中的 https://github.com/MisicDemone/formily/tree/feat-element/packages/element

成熟后会向formily提交pr

**Comment by muuyao** [comment]
@MisicDemone element 接入这个现在还有啥todo么？看了下貌似都开发完了，有啥可以帮忙pr下的

**Comment by wsxe9988** [comment]
ant design vue  有没有人开发接入formily呢

**Comment by MisicDemone** [comment]
> @MisicDemone element 接入这个现在还有啥todo么？看了下貌似都开发完了，有啥可以帮忙pr下的

1. 可以试用一下，看看有没有bug
2. 由于form-item是仿照formily/antd实现的，样式上和element不能完全匹配，还需要改进
3. upload组件还未适配
4. 文档、用例还未补充
