### ISSUE TITLE
[Bug Report] 给字段设置了readOnly后，设置字段对应component的mapReadPretty（阅读态） 失效

### ISSUE THREAD

**Issue by hugo429586472** [alibaba/formily#1585]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-pascal-iui5y?file=/src/App.vue)

### Steps to reproduce
设置input组件在readPretty模式下的渲染样式（如： mapReadPretty((props) => <div>{props.value}</div>) ）

给使用input组件的某个字段设置readOnly属性（无论是设置false还是设置true）

### What is expected?
form.pattern = readPretty 时组件能正常按照设置的 mapReadPretty 阅读态下 的渲染样式 进行渲染

### What is actually happening?

结果为 form.pattern = readPretty  的情况下还是显示的input输入框，而不是显示 mapReadPretty中设置的渲染样式

### Package
@formily/vue@2.0.0-beta.65

---

form.pattern进行切换时，组件还是进行 渲染的切换（如editable 切换到 readPretty）

readOnly只需要影响form.pattern = editable 或者 filed.pattern = editable 这个交互模式，其他交互模式（readPretty/disable）应该不会受影响

**Comment by MisicDemone** [comment]
这个应该是因为同时设置了field的pattern和form的pattern，而field的pattern优先级更高，所以采用了field上设置的readonly

**Comment by hugo429586472** [comment]
![image](https://user-images.githubusercontent.com/40160972/122337036-525c4e80-cf70-11eb-9fbf-3ae98a2a62b2.png)

我codesanbox的示例里是没有直接设置field的pattern的，还是说field的readOnly 会影响field的pattern？
readOnly我看是定义为 字段是否只读，而只读不应该 影响表单交互模式（编辑态、阅读态），应该是 只对应 编辑态下的 某个字段能否编辑吧？

**Comment by hugo429586472** [comment]
看了下pattern的文档，里面的确是有readOnly的交互模式，为什么要把readOnly也视为一种交互模式呢，这里readOnly和disable有什么区别。
我现在的业务场景是 需要有个详情页面，采用的是readPretty 阅读态，想要的是 详情页面也可以直接切换pattern到 editable编辑态 ，所以各种参数配置都是和编辑页面一致的（包括 readOnly参数），这就导致了 详情页面无法正常显示 设置了readOnly参数的字段（会永远显示为readOnly态）。
理论上也可以通过在 readPretty 阅读态时清除readOnly参数，切换pattern到 editable编辑态时才加上 来处理这个情况，但是感觉这样很麻烦，也不是很合理。

**Comment by MisicDemone** [comment]
目前schema中的readOnly在渲染时是会被当做field的readOnly属性的([transformer.ts](https://github.com/alibaba/formily/blob/formily_next/packages/json-schema/src/transformer.ts#L224))，在你的这个场景里，表单状态应该是由form来控制的，而不应该写在schema里。

此处的问题其实不在于 readOnly 是不是一种交互模式，它其实只是一个表单状态，JSON Schema本身也是有定义 readOnly 字段的（[JSON Schema 规范](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.4)）。对于表单状态来说，某个 field 被单独设置了不可编辑，那它就是不可编辑的，哪怕form的状态时 editable，因为field 自身的状态是优先级更高的。

这里可能产生困惑的地方是 Formily 将描述数据结构的配置和描述UI的配置合成了一个，使得readOnly在描述字段属性的同时还对UI有一定影响，这种方式自然是有利有弊的，这个话题甚至可以单开一个discussion来讨论。

**Comment by hugo429586472** [comment]
field 自身的状态是优先级更高的 这点没有疑问，的确应该是这样的。
那对于 readOnly在描述字段属性的同时还对UI有一定影响，这个形式是已经基本确定的 还是 只是初期这样定义。感觉readOnly这个与editable、readPretty相比 不太符合 pattern 表单交互模式 这个对象的定义。
因为readOnly本质不会是一套全新的交互逻辑，它应该是对于 editable这个状态下的一种补充说明或配置。而且实际上，formily目前的处理也的确是这样的，对于pattern 是readOnly的field，formily是没有定义一套全新的 UI和逻辑的，实际做法是给 editable状态下的componet传入了个readOnly=true的参数，也就是依附于editable 进行了一些额外的配置。
对于目前的这个实现，就感觉readOnly与editable不是一个平行的关系，是一个依附的关系。

**Comment by janryWang** [comment]
> field 自身的状态是优先级更高的 这点没有疑问，的确应该是这样的。
> 
> 那对于 readOnly在描述字段属性的同时还对UI有一定影响，这个形式是已经基本确定的 还是 只是初期这样定义。感觉readOnly这个与editable、readPretty相比 不太符合 pattern 表单交互模式 这个对象的定义。
> 
> 因为readOnly本质不会是一套全新的交互逻辑，它应该是对于 editable这个状态下的一种补充说明或配置。而且实际上，formily目前的处理也的确是这样的，对于pattern 是readOnly的field，formily是没有定义一套全新的 UI和逻辑的，实际做法是给 editable状态下的componet传入了个readOnly=true的参数，也就是依附于editable 进行了一些额外的配置。
> 
> 对于目前的这个实现，就感觉readOnly与editable不是一个平行的关系，是一个依附的关系。

不是依附关系，这个不用过多讨论，readOnly disable editable readPretty都是ui交互形态，且是互斥的，不可能既是editable又是readOnly，也不可能即是disabled又是readPretty

**Comment by hugo429586472** [comment]
如果是要定义readOnly disable editable readPretty 互斥的，可以让使用方自己定义一下readOnly形态的UI吗？类似使用 mapReadPretty 方法定义 readPretty状态的UI（比如叫mapReadOnly），而不是直接使用editable的UI再传一个readOnly参数进去。

**Comment by janryWang** [comment]
> 如果是要定义readOnly disable editable readPretty 互斥的，可以让使用方自己定义一下readOnly形态的UI吗？类似使用 mapReadPretty 方法定义 readPretty状态的UI（比如叫mapReadOnly），而不是直接使用editable的UI再传一个readOnly参数进去。

readOnly是组件的标准属性，也是HTML的规范，具体UI实现，你的组件从props上是可以读到的

**Comment by hugo429586472** [comment]
所以这里就产生了些疑惑，readOnly是组件的标准属性，pattern = readOnly 实际做的东西也就是将readOnly 参数传到组件里。

而editable 和 readPretty，是对 使用的组件 这一层进行定义的（定义使用什么组件），感觉就和 readOnly 的效果不在一个层面上。

**Comment by hugo429586472** [comment]
目前的场景是，我详情页和新增/编辑页都是使用的同一套 schema，这套schema里有某几个字段是 readOnly只读的。

对于详情页来说，无论这个字段是否只读，在详情页显示的样式就应该是 对应readPretty 阅读态的样式。
只有在新增编辑页上，只读的字段才会显示为 editable编辑态下的组件样式 且处于只读的形式。

**Comment by janryWang** [comment]
为什么 readOnly 会是 pattern的一种ui交互形态，而不是类似 require这样的 一个代表字段某种属性的参数。

本来readOnly/disabled/editable就是属于交互形态，第一次遇到对这个有疑问的，难道你配置了editable，还要配置readOnly？没懂你的需求场景，而且我这边也是同一份schema用在编辑详情里的

**Comment by hugo429586472** [comment]
同一份schema用在编辑详情里的时候，如果某个字段设置了readOnly属性，比如一个使用Input组件的字段，那在详情里不是会显示为 input组件 而不是 设置的readPretty的样式 这样吗？

**Comment by janryWang** [comment]
> 同一份schema用在编辑详情里的时候，如果某个字段设置了readOnly属性，比如一个使用Input组件的字段，那在详情里不是会显示为 input组件 而不是 设置的readPretty的样式 这样吗？

你是希望编辑场景走readOnly,详情走readPretty？这个是你业务逻辑控制的，formily感知不到你是详情还是编辑，需要你动态传参给它，通过表达式，把当前页面模式传给这个字段就行了，比如x-pattern:"{{mode = 'DETAIL' ? 'readPretty' : 'readOnly'}}"

**Comment by hugo429586472** [comment]
通过表达式，把当前页面模式传给这个字段就行了，比如x-pattern:"{{mode = 'DETAIL' ? 'readPretty' : 'readOnly'}}"
这样的确可以的，不过感觉就有点重重的，如果的确是这样定义的也没办法只能这样处理了。

感觉 编辑场景走readOnly,详情走readPretty 这个应该也挺常见的吧，你们那边业务需求不是这样的么。

**Comment by janryWang** [comment]
这不是重，这是最佳实践！因为formily感知不到你的页面模式，不同的模式下组件交互形态可能不一样，文案也可能不一样，联动不一样，通过注入上下文是最合理且容易理解的

**Comment by hugo429586472** [comment]
嗯，想了下readOnly的确还会影响到组件间互相交互和联动之类的，的确定义为一个独立的模式比较合理。

我这块业务逻辑用 把当前页面模式传给这个字段 的方式来解决吧。

**Comment by MeetzhDing** [comment]
> > 如果是要定义readOnly disable editable readPretty 互斥的，可以让使用方自己定义一下readOnly形态的UI吗？类似使用 mapReadPretty 方法定义 readPretty状态的UI（比如叫mapReadOnly），而不是直接使用editable的UI再传一个readOnly参数进去。
> 
> readOnly是组件的标准属性，也是HTML的规范，具体UI实现，你的组件从props上是可以读到的，为什么readPretty需要mapReadPretty是因为，它是Formily扩展的，所以需要特殊处理，而不是直接透传到props上

对于 readPretty, 可以在 ReactiveField.ts 中直接透传下来吗？

在绝大多数场景中，disabled 和 readOnly 应该都是没啥区别的，常见的组件库中，基本也只有**很少量的组件支持 readOnly 属性**，这个属性的功能性应该是比较弱的。但是 readPretty 却是一个不错的业务概念。

业务开发中，想要直接在一个组件内部完整描述所有的UI展示形态，也是比较常见的诉求。
开发者编写 field.editable 为 false 以后，readPretty 变成了 true，但是组件本身消费它却还要额外包裹一层 mapReadPretty
