### ISSUE TITLE
[Bug Report] FormButtonGroup.FormItem中的submit按钮多了冒号

### ISSUE THREAD

**Issue by Rhuaer** [alibaba/formily#1624]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-stallman-thyzd?file=/App.tsx:7809-7833)

### Steps to reproduce
提交按钮的左侧有冒号

1. 参见复现链接，代码的L335
2. 就算参照文档，加上了colon={false} 也无效

### What is expected?
1. 加上了colon={false} 之后，按钮左侧的冒号消失
2. 最好是不用设置，FormButtonGroup.FormItem 应该默认让冒号消失

### What is actually happening?
提交按钮的左侧有冒号

### Package
@formily/antd@2.0.0-beta.69

---

**Comment by janryWang** [comment]
Fixed

**Comment by Rhuaer** [comment]
@janryWang 
我看了一下代码，冒号出现的条件：
`colon: props.colon || layout.colon,`
文档中layout.colon默认也是true，所以如果只是设置formItem.colon为fasle，那么还是显示冒号的
可以参见这个复现的L104，如果我的配置没写错的话，那么设置了formItem.colon为fasle，那还是出现了冒号，不符合预期

**Comment by janryWang** [comment]
嗯，多谢提醒，这个其实又是另外一个Bug了，待会我再提交一版
