### ISSUE TITLE
[Bug Report] 当字段指定了 `'x-hidden': true` 时，设置其内部字段的值和初始值表现不正确

### ISSUE THREAD

**Issue by JustDs** [alibaba/formily#1644]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/set-values-when-hidden-jqk3l?file=/App.tsx)

### Steps to reproduce
1. 观察初始状态的表单值

2. 点击 setInitialValues() 按钮，观察表单值

2. 点击 setValues() 按钮，观察表单值

### What is expected?
`object-1.array-1` 和 `object-2.array-2` 的值都始终保持为 `[]`

### What is actually happening?
`object-1.array-1` 的值始终保持为 `[]`，`object-2.array-2` 的值先后变为 `undefined`、`null`、`{}`

### Package
@formily/react@2.0.0-beta.71

---

按文档的描述：
https://github.com/alibaba/formily/blob/fead78439e0d1cbe8883544f53cf64aaf9877bc3/packages/core/docs/guide/field.md#L53
无论 hidden 与否，应该不影响表单的数据才对，但实际上会导致预期之外的赋值。

**Comment by janryWang** [comment]
来个PR？

**Comment by JustDs** [comment]
这问题没那么简单吧，跟 Formily React 的策略有关，如果 hidden 的话导致 RecursionField 根本不会渲染，也就意味着子级的 Field 都不会被创建了，所以才会有这个问题。

但是这个问题我觉得是个设计上的问题而不是实现上的问题，得看看怎么处理。

**Comment by janryWang** [comment]
这个还是使用上的反模式，都手动设置值了，为啥不能保证数据的正确性，而是要求formily来帮你纠正值呢？formily的设计，就是希望惰性求值，这样性能会更好，各有侧重点吧，设计上也是需要权衡的

**Comment by JustDs** [comment]
数据的正确性问题指的是向 array 类型字段赋值 null？

**Comment by JustDs** [comment]
首先 null 值不是我填充的，而是后台接口填充的，如果我需要把 null 处理掉是不是意味着我需要额外垫一层？

其次，即使抛开 null 的问题不谈，单纯只看初始状态，hidden 和非 hidden 状态下的取值也是不同的，这点无关于惰性求值。

**Comment by janryWang** [comment]
这跟hidden没关系的，你只需要在设置initialValues的时候改成这样即可
```
form.setInitialValues({
    "object-1": {
      "array-1": []
    },
    "object-2": {
      "array-2": []
    }
  });
```

**Comment by janryWang** [comment]
顺便说一下，你是遇到什么问题了？具体是什么场景，以后尽量在提这种模糊性问题的时候先说明清楚具体场景，不然很难判断是设计的问题还是用法问题

**Comment by JustDs** [comment]
行，如果你想要具体场景那我就告诉你具体场景吧：

一个大的配置表单，上面一个选项分为两种类型，每种类型下面一堆要配的。选项选其中一边的时候另一边是空的，某个 array 字段提交了 `undefined`（JSON 序列化就是没这字段了），后台往里填了 `null`。二次编辑回填的时候，用 `setInitialValues()` + `setValues()` 把值塞回表单里，再提交就变了 `{}`，后台校验类型报错。

单就这个问题的话，我已经把 `setValues()` 去了就没事了。

如果你想说合理的用法就是只用 `setInitialValues()`，我认可。但是我也不觉得 `setInitialValues()` + `setValues()` 是个从常理上讲 / 有明确官方说明的不合理的用法。

**Comment by janryWang** [comment]
你的意思是，前端给后端传的是undefined，后端回填了一个null，然后数据就出问题了是吧？

**Comment by JustDs** [comment]
前端没挂掉，但是提交给后台本来应该是数组的字段变成了 `{}`，后台报错了

**Comment by janryWang** [comment]
不对呀，数组怎么可能会变成对象，只能说是它上一层的数据传上去了，array那一个节点的数据是null,本身就是和后端传下来的数据是幂等的

**Comment by JustDs** [comment]
你是不是理解错了，一个 hidden 的字段，我给后台 undefined，后台给我 null，写到 formily 变成了 `{}`，再给后台也成了 `{}`，后台报错

**Comment by JustDs** [comment]
至于为什么会变成 `{}`，这就是我提这个 issue 的原因啊。

**Comment by janryWang** [comment]
晕，你这个问题扯了一大圈，其实是setValues里的defaults合并策略有Bug而已，跟hidden没关系
