### ISSUE TITLE
[Bug Report] ArrayItems Editable.Popover在编辑模式下添加新记录调整排序会对原数据最后一条记录造成数据污染

### ISSUE THREAD

**Issue by sotoup** [alibaba/formily#1654]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-varahamihira-vxi1x?file=/App.tsx:4441-4457)

### Steps to reproduce
[场景案例] 编辑详情Json Schema示例 
1. 点击 新增联系人
2. 点击 完善联系人信息，在PopOver界面输入
    王五
    wang@163.com
    13800000000
3. 拖动排序 调整新记录到顶部
4. 点击 最后一条记录 查看数据，除了标题显示正常外，实际数据却与新添加的数据一样

![issue_step_1.png](https://i.loli.net/2021/06/28/rByb615Iid7sGKk.png)
![issue_step_2.png](https://i.loli.net/2021/06/28/LtQ5cgSEJ1eRMW6.png)
![issue_step_3.png](https://i.loli.net/2021/06/28/5ZpMcNoIV7LWg1d.png)
![issue_step_4.png](https://i.loli.net/2021/06/28/evfsDSQKzaEkC8U.png)

### What is expected?
新添加的记录 不管如何拖动排序 不会对任何原始记录产生影响

### What is actually happening?
新添加的记录拖动排序会对原数据最后一条记录造成数据污染

### Package
@formily/antd@2.0.0-beta.72

---

**Comment by janryWang** [comment]
多谢反馈
