### ISSUE TITLE
[Bug Report] ArrayTable 多选选中项删除后选中状态错乱问题

### ISSUE THREAD

**Issue by BernardZhang** [alibaba/formily#1750]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-kowalevski-ythqv?file=/index.js)

### Steps to reproduce
1. 选中第二条
2. 删除第二条
3. 第二条删除后，原来的第三条变成选中状态了

### What is expected?
使用者可以自定义rowKey, 把componentProps 放到rowKey的下面，让使用者可以定义rowKey
```
const renderTable = () => {
      return (
        <Table
          {...componentProps}
          rowKey={record => {
            return toArr(value).indexOf(record)
          }}
          pagination={false}
          columns={columns}
          dataSource={toArr(value)}
        ></Table>
      )
    }

```

### What is actually happening?
使用者无法设置Table的 rowKey

### Package
@formily/antd-components@1.3.17

---

**Comment by janryWang** [comment]
不支持ArrayTable多选
