### ISSUE TITLE
[Bug Report] 容器样式选择报错

### ISSUE THREAD

**Issue by wawow** [alibaba/formily#1778]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily)

### Steps to reproduce
打开https://designable-antd.formilyjs.org/
拖动input输入框到编辑器中
选择右侧容器样式，点开边框
react-dom.development.js:61 Warning: Cannot update a component (`Unknown`) while rendering a different component (`Field`). To locate the bad setState() call inside `Field`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at t.Field (https://designable-antd.formilyjs.org/playground.45f25c9b90a9048885fc.bundle.js:6:1487126)
报错异常

### What is expected?
功能正常使用不报错

### What is actually happening?
功能正常使用，代码报错

### Package
@formily/antd@2.0.0-beta.77

---

**Comment by janryWang** [comment]
不是Formily这边的Bug，是designable的

**Comment by wawow** [comment]
那这个可以提交到哪去解决呢？
