### ISSUE TITLE
[Bug Report] 表单联动失效

### ISSUE THREAD

**Issue by zkylearner** [alibaba/formily#1815]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/billowing-forest-rmh6f?file=/App.tsx)

### Steps to reproduce
x-reactions的dependencies数组值类型为数字时，表单项联动失效

### What is expected?
支持数字类型及其他类型的处理

### What is actually happening?
代码中未处理 number 类型，导致联动失效

### Package
@formily/core@2.0.0-beta.78

---

**Comment by janryWang** [comment]
不打算支持数字了，一开始就只考虑匹配字符串路径
