### ISSUE TITLE
[Bug Report] 自定义webpack配置时@formily/antd中DatePicker国际化失效

### ISSUE THREAD

**Issue by lovewinders** [alibaba/formily#1830]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/lovewinders/webpack5-formily-bug-demo)

### Steps to reproduce
第一步：自定义webpack.config.js

第二步：webpack entry 入口文件index.js设置如下

import moment from 'moment'

import 'moment/locale/zh-cn';

moment.locale('zh-cn')

第三步：App组件

import React from 'react';

import { ConfigProvider, DatePicker as DatePickers } from 'antd';

import { DatePicker } from '@formily/antd';

import zhCN from 'antd/lib/locale/zh_CN';

export default (props) => {

    return (
        <ConfigProvider locale={zhCN}>
            <h1>自定义webpack配置，@formily/antd中DatePicker国际化失效Demo</h1>
            @formily/antd:
            <br/>
            <DatePicker />
            <br/>
            <br/>
            antd:
            <br/>
            <DatePickers />
        </ConfigProvider>
    );

};

### What is expected?
期望@formily/antd中DatePicker国际化正常

### What is actually happening?
实际@formily/antd中DatePicker国际化失效（antd的DatePicker国际化时正常的）
![1626694480247](https://user-images.githubusercontent.com/22837419/126154267-1f23fa7a-a838-447b-8155-752da51dceee.jpg)

### Package
@formily/antd@2.0.0-beta.80

---

**Comment by janryWang** [comment]
只有DatePicker有问题吗

**Comment by lovewinders** [comment]
> 只有DatePicker有问题吗

目前项目中只涉及到formmily的DatePicker组件，这个在自定义webpack里是有国际化问题的，但是奇怪的是codesandbox里运行formmily的DatePicker组件国际化是正常的。

**Comment by janryWang** [comment]
你先试试其他组件国际化有没有问题，比如Transfer

**Comment by lovewinders** [comment]
> 你先试试其他组件国际化有没有问题，比如Transfer

你可以去上边git demo链接运行看下效果，我现在已经下班了，明天我看看其他组件，我临时解决方案是用formily/antd DatePicker属性props的locale来局部解决国际化问题也能达到目的，但是全局确实存在问题，目前只能临时局部设置解决问题。

**Comment by javahuang** [comment]
@lovewinders 示例代码跑不起来

**Comment by lovewinders** [comment]
> @lovewinders 示例代码跑不起来

npm i
npm run dev

**Comment by lovewinders** [comment]
> @lovewinders 示例代码跑不起来

你再重新拉取一下git代码就可以跑了。

**Comment by lovewinders** [comment]
@janryWang @formily/antd中Transfer国际化也有问题，我刚试了下。示例代码中已加Transfer

**Comment by janryWang** [comment]
晕死，你这个是重复打包了，你给antd配置的babel-import-plugin没有指定es目录，导致它默认加载的lib下的模块，但是formily内部是没有按需打包的，走webpack默认加载机制，走的是es目录，两个配不上了，总之，多看看文档吧 https://v2.formilyjs.org/zh-CN/guide/advanced/build

**Comment by zxq08** [comment]
> 晕死，你这个是重复打包了，你给antd配置的babel-import-plugin没有指定es目录，导致它默认加载的lib下的模块，但是formily内部是没有按需打包的，走webpack默认加载机制，走的是es目录，两个配不上了，总之，多看看文档吧 https://v2.formilyjs.org/zh-CN/guide/advanced/build

哈喽想请教一下，我是基于umi/max开发的，我在externals中剔除了antd以及它的依赖，从cdn引入，导致我设置的主题token针对formily/antd-v5不生效了，请问下有什么解决办法
