### ISSUE TITLE
[Bug Report] 【antD-select】ts类型报错

### ISSUE THREAD

**Issue by aoilti** [alibaba/formily#1838]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/floral-rain-ekgjv?file=/App.tsx:411-741)

### Steps to reproduce
1、通过createSchemaField创建field
2、指定SchemaField的Compoment为Select
3、出现类型报错

### What is expected?
无类型报错

### What is actually happening?
类型不兼容报错

### Package
@formily/antd@2.0.0-beta.80

---

**Comment by janryWang** [comment]
Antd的类型问题
