### ISSUE TITLE
[Bug Report] treeSelect多选返回的value值的数据结构和antd不一致

### ISSUE THREAD

**Issue by li9269391** [alibaba/formily#1853]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-wozniak-emto0?file=/App.tsx)

### Steps to reproduce
多选，然后提交
![image](https://user-images.githubusercontent.com/10287877/126584282-4ea4fc6d-7812-45a4-bdee-d9b534ef8df5.png)

### What is expected?
返回 value 和 antd 定义的类型一致 string | string[]
[antd例子](https://codesandbox.io/s/kegouxuan-antd4168-forked-ezbjw)
![image](https://user-images.githubusercontent.com/10287877/126584541-2609e213-27ef-483d-a583-da2cbaff6fde.png)

### What is actually happening?
未知

### Package
@formily/antd@2.0.0-beta.80

---

**Comment by janryWang** [comment]
formily没做过数据转换，你最好先验证原生antd是否存在该问题

**Comment by li9269391** [comment]
[antd官例](https://codesandbox.io/s/kegouxuan-antd4168-forked-ezbjw)
有附加了官例，原生antd不会

**Comment by janryWang** [comment]
![image](https://user-images.githubusercontent.com/4060976/126588853-ec4e08fe-c48c-406e-83e0-208d7296610b.png)
文档都没看的么
