### ISSUE TITLE
[Bug Report] @formily/antd中的DatePicker及RangePicker不能设置默认数据

### ISSUE THREAD

**Issue by lck123357** [alibaba/formily#1888]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-morse-yixyp)

### Steps to reproduce
在x-component-props中设置defaultValue，因为是RangePicker，所以是一个数组

### What is expected?
能正常默认展示当前时间

### What is actually happening?
组件为空，无默认组件

### Package
@formily/antd@2.0.0-beta.82

---

看代码后发现无defaultValue这个属性，与antd中的使用不符

**Comment by janryWang** [comment]
不是bug，type需要指定array才能正确赋默认值，否则内核会作为普通字段来判空，解构场景比较特殊，解构的时候，会默认为[undefined,undefined]

**Comment by lck123357** [comment]
感谢！！！
