### ISSUE TITLE
[Bug Report] json-Schema中，Switch组件设置了checked：true，提交时，无法通过必填项校验

### ISSUE THREAD

**Issue by 156586197** [alibaba/formily#1949]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-shadow-4o571?file=/App.tsx)

### Steps to reproduce
我们给Switch设置了checked：true，直接点击登录。

### What is expected?
既然开关设置了checked，就应该通过表单必填项校验；

### What is actually happening?
实际上并没有。我们找到了一种方法可以解决这个问题，就是使用setInitialValues方法，但是表单返回的格式比较复杂，所以这样做感觉不太好。是不是我使用有问题，求助大佬！！！

### Package
@formily/antd@2.0.0-beta.80

---

**Comment by janryWang** [comment]
配置schema的default属性

**Comment by 156586197** [comment]
是在x-component-props里设置defaultChecked：true吗

**Comment by 156586197** [comment]
> 配置schema的default属性
是在x-component-props里设置defaultChecked：true吗

**Comment by janryWang** [comment]
都说了，配置schema的default属性，default

**Comment by 156586197** [comment]
> 都说了，配置schema的default属性，default

额，解决了，谢谢大佬，不吝赐教。
