### ISSUE TITLE
[Feature Request] 想知道怎么引入 designable 使用 

### ISSUE THREAD

**Issue by GadflyX** [alibaba/formily#1982]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
designable 还没有发布，但是官方文档下有安装其 npm 包的介绍，install 会报 404。
想知道在 designable 还没有发布的情况下，怎么引入使用 ？ fork 源码 ？

### What does the proposed API look like?
有个比较好的方式能引入 designable

**Comment by janryWang** [comment]
提问请到discussion
