### ISSUE TITLE
[Bug Report] tab切换后下拉输入失效

### ISSUE THREAD

**Issue by lvxiaoxing** [alibaba/formily#1986]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-butterfly-1rx4o?file=/index.js)

### Steps to reproduce
1，在第一个输入框输入1，按下enter，会选择‘1111-testa’项
2，按下Tab，切换到第二个输入框
3，输入2，下拉会出现过滤选项，但按下enter不会选中对应选项

### What is expected?
第三步，输入2，按下enter，选中“222-testb'项

### What is actually happening?
第三步，输入2，下拉会出现过滤选项，过滤项没有激活，且按下enter不会选中对应选项

### Package
@formily/antd@1.3.17

---

[已在antd的select的demo中做同样操作，不会出现该问题](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-16-11-forked-cffr0)

**Comment by janryWang** [comment]
formily1.x依赖的是antd3.x，我猜测是3.x的bug

**Comment by lvxiaoxing** [comment]
3.x 确实有这个问题，请问这个问题会在formily1.x 修复吗

**Comment by lvxiaoxing** [comment]
> formily1.x依赖的是antd3.x，我猜测是3.x的bug

3.x 确实有这个问题，请问这个问题会在formily1.x 修复吗

**Comment by janryWang** [comment]
不会，这是antd的问题

**Comment by lvxiaoxing** [comment]
> 不会，这是antd的问题

请问v2 会出现这个问题吗

**Comment by janryWang** [comment]
2.0是依赖antd4的，肯定没有这个问题呀

**Comment by lvxiaoxing** [comment]
> 2.0是依赖antd4的，肯定没有这个问题呀

请问 field 可以做成又可以输入，又可以下拉选择吗
