### ISSUE TITLE
[Bug Report] FormDialog无法手动控制不关闭

### ISSUE THREAD

**Issue by AngleJanice** [alibaba/formily#2017]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7y1zf)

### Steps to reproduce
点击“OK”保存保存，接口返回错误时，无法手动控制不关闭弹窗

### What is expected?
点击“OK”保存保存，接口返回错误时，无法手动控制不关闭弹窗

### What is actually happening?
点击“OK”保存保存，接口返回错误时，可以手动控制FormDialog弹窗关闭与否

### Package
@formily/antd@2.0.0-beta.80

---

针对FormDialog的confirmLoading属性使用无效，无法手动控制

**Comment by janryWang** [comment]
没懂你的问题，codesandbox请给能复现问题的例子

**Comment by AngleJanice** [comment]
我们有一个修改密码的表单，在提交表单的时候需要验证原密码是否正确，接口返回密码不正确的时候，我需要让FormDialog继续显示，而不是直接关闭。有没有方法可以手动控制这个FormDialog的显示和隐藏

**Comment by janryWang** [comment]
接口报错直接throw，中间件会catch error，自动阻止关闭，如果这个解决你的问题了，请自行close该issue

**Comment by AngleJanice** [comment]
进入catch后弹窗依旧会关闭

**Comment by janryWang** [comment]
要在中间件里发请求的

**Comment by janryWang** [comment]
你的例子我看不到你说的问题

**Comment by AngleJanice** [comment]
现在走到catch里面了，但是“确定”按钮的Loading状态取消不了，有什么办法取消“确定“按钮的loading状态？

**Comment by janryWang** [comment]
你先把codesandbox 完善好再提问
