### ISSUE TITLE
[Bug Report] 使用useField,标题没有显示

### ISSUE THREAD

**Issue by GeSnowBoy** [alibaba/formily#2045]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-wing-4g7md?file=/index.js:298-306)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/17561864/130772207-7e0a5093-04fe-4d48-9ca5-0b6a85abb3ea.png)

### What is expected?
期望标题展示

### What is actually happening?
使用了useField , 标题不能正常显示.

### Package
@formily/antd@2.0.0-rc.3

---

**Comment by janryWang** [comment]
1.x不支持通过useField获取上下文字段的写法，可以使用useSchemaProps

**Comment by janryWang** [comment]
1.x不支持通过useField获取上下文字段的写法，可以使用useSchemaProps

**Comment by GeSnowBoy** [comment]
@janryWang    我尝试在组件里面使用 useSchemaProps, 发现返回值为null.
而且 useField 在1.x 的文档里面有描述,目前只是,渲染的时候把标题给渲染没了. 能看下吗

**Comment by GeSnowBoy** [comment]
或者如果不用 useField ,我怎么在一个组件里面获取form的值呢?
 我的需求是这样的:  
 
![image](https://user-images.githubusercontent.com/17561864/130784963-aac3e350-7d46-4bf7-b00d-c74a95faeaee.png)
一个组件上传图片, 在下面一个组件使用选择的图片做选择.现在功能正常,但是标题没有了.

**Comment by janryWang** [comment]
哦，你这个不是schema场景，可以通过给自定义组件挂一个静态属性isFieldComponent为true，然后props就能拿到上下文

**Comment by GeSnowBoy** [comment]
@janryWang   感谢回复.  你说的方式我试了下好像没用. 不过我已经通过 useFormEffects 获取到了. 感谢你的帮助.

**Comment by janryWang** [comment]
嗯嗯，通过联动的方式是推荐的方式
