### ISSUE TITLE
[Feature Request] Implement makeAutoObservable like the latest MobX

### ISSUE THREAD

**Issue by cncolder** [alibaba/formily#2072]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://mobx.js.org/observable-state.html#makeautoobservable

### What does the proposed API look like?
```
class Store {
  constructor() {
    makeAutoObservable(this);
  }
}
```

**Comment by janryWang** [comment]
model === makeAutoObservable
