### ISSUE TITLE
[Feature Request] 支持表单嵌套渲染

### ISSUE THREAD

**Issue by Huhui-coder** [alibaba/formily#2073]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如，我目前遇到这样的一个场景：
JSON数据格式如下：
`
{
  "propsSchema": {
    "type": "object",
    "properties": {
      "name": {
        "title": "字段名",
        "type": "string"
      },
      "type": {
        "title": "类型",
        "type": "string",
        "items": {
          "type": "string"
        },
        "enum": ["A", "B", "C", "D"],
        "enumNames": ["Object", "Array", "number", "int"],
        "ui:widget": "Select"
      },
      "required": {
        "title": "必填",
        "type": "boolean"
      },
      "filed": {
        "type": "object",
        "properties": {
          "name": {
            "title": "字段名",
            "type": "string"
          },
          "type": {
            "title": "类型",
            "type": "string",
            "items": {
              "type": "string"
            },
            "enum": ["A", "B", "C", "D"],
            "enumNames": ["Object", "Array", "number", "int"],
            "ui:widget": "Select"
          },
          "required": {
            "title": "必填",
            "type": "boolean"
          }
        }
      }
    }
  }
}
`

每一个父元素下可能都有一个 `filed`字段，为上一个元素的嵌套类型。
![](https://i.bmp.ovh/imgs/2021/08/092a597f459743b5.png)
当点击父元素的 新增按键之后，下方新增一个表单项目(与父元素表单项结构是不一致的，并且该子元素的数据要嵌套到父元素的filed字段下，并且根据父元素的type 字段参数渲染不同的子元素表单项。）目前依据 formily  所提供的方案，我没有找到合适的案例，请问有其他的操作，能实现我目前的需求吗？谢谢。

### What does the proposed API look like?
`
  <ArrayList.Addition
              index={index}
              onClick={() => mutators.insert(${index}, ${initValue}, ${FormItem}}
            />
`
我希望能直接提供一个 insert 方法，当在父元素列表页点击新增时，是在父元素的JSON结构下进行新增的，且是嵌套的。并且API 默认支持传入三个参数; index: 插入的位置，initValue: 子元素初始化的值，FormItem: 插入的 表单项(使用antd进行渲染)。

**Comment by janryWang** [comment]
为什么需要嵌套表单，你这个需求就是个自增列表组件

**Comment by Huhui-coder** [comment]
> 为什么需要嵌套表单，你这个需求就是个自增列表组件

不是呀，我这个是嵌套的，当父级是 Object 类型时，是支持嵌套的。一个完整的 数据结构类似下面这样。
`{
  "propsSchema": {
    "type": "object",
    "properties": {
      "name": {
        "title": "字段名",
        "type": "string"
      },
      "type": {
        "title": "类型",
        "type": "string",
        "items": {
          "type": "string"
        },
        "enum": ["A", "B", "C", "D"],
        "enumNames": ["Object", "Array", "number", "int"],
        "ui:widget": "Select"
      },
      "required": {
        "title": "必填",
        "type": "boolean"
      },
      "filed": {
        "type": "object",
        "properties": {
          "name": {
            "title": "字段名",
            "type": "string"
          },
          "type": {
            "title": "类型",
            "type": "string",
            "items": {
              "type": "string"
            },
            "enum": ["A", "B", "C", "D"],
            "enumNames": ["Object", "Array", "number", "int"],
            "ui:widget": "Select"
          },
          "required": {
            "title": "必填",
            "type": "boolean"
          }
        }
      }
    }
  }
}`

**Comment by janryWang** [comment]
formily json-schema天然就支持嵌套，麻烦先看看文档

**Comment by Huhui-coder** [comment]
> formily json-schema天然就支持嵌套，麻烦先看看文档
没有找到这种 表单嵌套 的实例呢，能给个例子吗，麻烦了。

**Comment by Huhui-coder** [comment]
> formily json-schema天然就支持嵌套，麻烦先看看文档
没有找到这种 表单嵌套 的实例呢，能给个例子吗，麻烦了。

**Comment by janryWang** [comment]
文档多看看吧，组件文档ArrayTable/ArrayCards，都是支持嵌套的组件，实在搞不懂，就试试用一下formily设计器，上面可以嵌套搭建
