### ISSUE TITLE
[Bug Report] 360极速浏览器下表单的输入框等宽度撑不开

### ISSUE THREAD

**Issue by lxzy-yun** [alibaba/formily#2154]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7ql5g)

### Steps to reproduce
官方地址也是这样的问题 https://fusion.formilyjs.org/components/form

### What is expected?
输入框等宽度100%

### What is actually happening?
输入框等宽度默认200

### Package
@formily/next@2.0.0-rc.7

---

**Comment by janryWang** [comment]
来个PR吧，我这边没有windows系统，测试不了
