### ISSUE TITLE
[Bug Report] <SchemaField path={FormPath.parse(path).concat(index)} /> 显示隐藏数据丢失

### ISSUE THREAD

**Issue by rainbowsuger** [alibaba/formily#2166]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily)

### Steps to reproduce
ArrayList中设置变空控制SchemaField显示隐藏，
<ArrayList
      components={ArrayButtons}
      renders={{
        renderAddition,
        renderRemove,
      }}
    >
      
      {toArr(value).map((item, index) => {
        return (
              {active === index && <SchemaField path={FormPath.parse(path).concat(index)} />}
        )
      })}
      
    </ArrayList>

### What is expected?
预期正确显示数据

### What is actually happening?
隐藏在显示数据丢失

### Package
@formily/shared@1.0.4

---

抱歉，链接我随便写的

**Comment by janryWang** [comment]
请给codesandbox复现地址
