### ISSUE TITLE
[Bug Report] json-schema，延迟设置Select组件的enum属性，下拉选项列表是空的

### ISSUE THREAD

**Issue by Rhuaer** [alibaba/formily#2225]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-engelbart-y2y9e?file=/App.tsx)

### Steps to reproduce
1. 开始设置性别的enum数据是空数组
2. 利用useEffect，且使用setTimeout，设置3秒后，给性别字段的enum属性赋值，并使用setState重新更新schema

### What is expected?
延迟设置enum属性，会有下拉列表数据

### What is actually happening?
现在是在RecursionField上能看到enum属性有数据，但下拉列表没有数据

### Package
@formily/react@2.0.0-rc.10

---

**Comment by janryWang** [comment]
不是Bug，看受控表单文档

**Comment by BillJC-Liu** [comment]
@janryWang 可否附上受控表单文档链接
