### ISSUE TITLE
[Bug Report] FormGrid  的 maxWidth 参数无效

### ISSUE THREAD

**Issue by liuweiGL** [alibaba/formily#2390]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-bohr-tun6z?file=/App.tsx)

### Steps to reproduce

1. 打开 Codesandbox
2. F12 打开控制台查看元素的尺寸

### What is expected?
GridItem  的最大宽度不要超过 120px

### What is actually happening?
GridItem 的尺寸可以突破设定的 maxWidth

![1635929539(1)](https://user-images.githubusercontent.com/21048878/140032227-a4041451-af9f-452d-879a-db9c9fc2e395.jpg)

### Package
@formily/grid@2.0.0-rc.17

---

**Comment by janryWang** [comment]
故意这样的，因为希望保持整体严丝合缝，如果在宽度满足的情况下是以maxWidth为准，不满足了，就以严丝合缝为准

**Comment by liuweiGL** [comment]
调整之前：
![image](https://user-images.githubusercontent.com/21048878/140033611-953c371a-cc4f-4fc1-9626-a6cce092f38c.png)
![image](https://user-images.githubusercontent.com/21048878/140033826-dfcf18e2-fac8-46e5-8186-b8329d30babf.png)

调整之后：
![image](https://user-images.githubusercontent.com/21048878/140033656-cd7e955f-64ac-4d76-855b-52f500f4b01f.png)
![image](https://user-images.githubusercontent.com/21048878/140033954-327f9c98-ad8b-46b1-a36b-c467557982a8.png)

**Comment by liuweiGL** [comment]
看查询条件的 input 宽度，这个特性我感觉不具备通用性。

**Comment by liuweiGL** [comment]
```ts
  get templateColumns() {
    if (!this.width) return ''
    if (this.maxWidth === Infinity) {
      return `repeat(${this.columns},1fr)`
    }
    const columnWidth =
      (this.width - (this.columns - 1) * this.columnGap) / this.columns
    if (columnWidth < this.minWidth || columnWidth > this.maxWidth)
      return `repeat(${this.columns},1fr)`
    return `repeat(${this.columns},minmax(${this.minWidth}px,${this.maxWidth}px))`
  }
```

我认为这个逻辑中 maxWidth 是没有意义的，不管是小于还是大于都跟 maxWidth 没关系。

**Comment by janryWang** [comment]
要不你这边提个PR？增加个属性开关，控制是否走严丝合缝？因为我这边需要严丝合缝...

**Comment by liuweiGL** [comment]
恩，好。

**Comment by liuweiGL** [comment]
我忽然想到，maxWidth 设置为 Infinity 不就是严丝合缝的吗？

**Comment by janryWang** [comment]
默认就是 Infinity的，这里做了默认处理

**Comment by liuweiGL** [comment]
对呀，那就不需要再添加额外的属性呗，需要占满容器设置 maxWidth 就好了。

 if (columnWidth < this.minWidth || columnWidth > this.maxWidth)
      return `repeat(${this.columns},1fr)`

这个处理删掉就可以吧？

**Comment by janryWang** [comment]
不对吧，严丝合缝强依赖`repeat(${this.columns},1fr)`里的1fr

**Comment by liuweiGL** [comment]
我的意思是如果需要严丝合缝的效果， FormGrid 设置 maxWidth=Infinity 就可以了：
```ts
   if (this.maxWidth === Infinity) {
      return `repeat(${this.columns},1fr)`
    }
```
这个判断返回了需要的样式。

**Comment by janryWang** [comment]
> 我的意思是如果需要严丝合缝的效果， FormGrid 设置 maxWidth=Infinity 就可以了：
> 
> ```ts
>    if (this.maxWidth === Infinity) {
>       return `repeat(${this.columns},1fr)`
>     }
> ```
> 
> 这个判断返回了需要的样式。

你的意思是要把默认Infinity的逻辑干掉？

**Comment by liuweiGL** [comment]
> 要不你这边提个PR？增加个属性开关，控制是否走严丝合缝？因为我这边需要严丝合缝...

晕了~
你不是让我加个属性开关吗？我的意思是不需要加。
因为设置 maxWidth 属性为 Infinity 就可以达到严丝合缝的效果，无需额外的属性控制。
然后我提个 PR 把：
```ts
  if (columnWidth < this.minWidth || columnWidth > this.maxWidth)
      return `repeat(${this.columns},1fr)`
```
这个判断去掉就好了。

**Comment by janryWang** [comment]
不对啊，我需要的是，如果满足maxWidth的要求，就走maxWidth约束，不满足才走1fr，这里面有个策略的，而不是一刀切全部走1fr

**Comment by liuweiGL** [comment]
假设 minWidth=100，maxWidth=300，columns=3；
当 columnWidth=200 的时候样式为 `repeat(3,minmax(100px,200px))`，当 columnWidth 为 400 的时候样式为 `repeat(3,1fr)`。
那现在有一个问题就是 columnWidth<maxWidth 的时候，`repeat(3,minmax(100px,200px))` 跟 `repeat(3,1fr)` 有区别吗？

**Comment by janryWang** [comment]
columnWidth是动态算出来的，它是按照列数来算的，列数会动态变，因为每个容器宽度下会尽可能的求出可塞满的列数，只有塞不满了才会走1fr逻辑

**Comment by liuweiGL** [comment]
不管它是不是算出来的啊，问题是一样的。
假设容器的宽度是 width=1200，columnGap=0（GridItem 之间没有间隙），minWidth=100，maxWidth=300；

当 columns=2 时，columnWidth=600，`columnWidth > this.maxWidth`  成立，返回  `repeat(2,1fr)`
当 columns=3 时，columnWidth=400，`columnWidth > this.maxWidth`  成立，返回  `repeat(3,1fr)`
当 columns=4 时，columnWidth=300，`columnWidth > this.maxWidth`  不成立，返回 repeat(4,minmax(100px,300px))
当 columns=5 时，columnWidth=240，`columnWidth > this.maxWidth`  不成立，返回 repeat(5,minmax(100px,300px))

以上所有情况的**展示效果都是 GridItem 占满整个容器**，`columnWidth > this.maxWidth` 这个比较没有任何意义。
因为 `columnWidth < this.maxWidth` 时，`repeat(${this.columns},minmax(${this.minWidth}px,${this.maxWidth}px))` 跟 `repeat(${this.columns},1fr)` 的展示效果是一样的。

**Comment by liuweiGL** [comment]
```
  get templateColumns() {
    if (!this.width) return ''
    if (this.maxWidth === Infinity) {
      return `repeat(${this.columns},1fr)`
    }
    // const columnWidth =
    //   (this.width - (this.columns - 1) * this.columnGap) / this.columns
    // if (columnWidth < this.minWidth || columnWidth > this.maxWidth)
    //   return `repeat(${this.columns},1fr)`
    
    return `repeat(${this.columns},minmax(${this.minWidth}px,${this.maxWidth}px))`
  }

```
把这个判断去掉即可。

你要 GridItem 占满容器（严丝合缝的效果）只需要把 maxWidth 设置为 Infinity 就好了。
