### ISSUE TITLE
[Bug Report] 折叠版面内，使用网格布局。操作折叠版面后，默认值消失

### ISSUE THREAD

**Issue by fuzhifr** [alibaba/formily#2413]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-paper-dhr45?file=/index.tsx)

### Steps to reproduce
渲染后，点击收起折叠版面，再打开

### What is expected?
打开折叠版面，重新渲染组件的默认值

### What is actually happening?
组件默认值丢失

### Package
@formily/antd@2.0.0-rc.17

---

**Comment by janryWang** [comment]
不是Bug，这个问题原因是给折叠面板传了type="object"，但是折叠面板本身是有onChange事件的，折叠切换的时候会触发，并会刷掉object的值
