### ISSUE TITLE
[Bug Report] FormItem 的gridSpan失效

### ISSUE THREAD

**Issue by Nokecy** [alibaba/formily#2467]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-curran-0v9ed?file=/App.tsx)

### Package
@formily/antd@2.0.0-rc.20

---

rc18是可以的 rc19以后就不行了

**Comment by Nokecy** [comment]
额 2.0 还是一样 https://codesandbox.io/s/beautiful-curran-0v9ed?file=/App.tsx

**Comment by janryWang** [comment]
不是bug，这种会自动修正gridSpan的，如果你非要换行，可以给前面两个column指定span 2
