### ISSUE TITLE
[Bug Report] vue2 ArrayCollapse 点击折叠会报错 Invalid value used as weak map key

### ISSUE THREAD

**Issue by qiangguoguo** [alibaba/formily#2509]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9q2h6?file=/src/App.vue)

### Steps to reproduce
1. 点击添加条目按钮，再点击右上角的折叠箭头，此时 input 输入框会消失

2. 再点击添加条目按钮，然后点击右上角的折叠箭头， console 会报错 [Vue warn]: Error in render: "TypeError: Invalid value used as weak map key"，input 输入框不能输入内容

### What is expected?
可以正常折叠不报错

### What is actually happening?
折叠按钮报错，且输入框无法正常输入内容

### Package
@formily/element@2.0.0

---

**Comment by muuyao** [comment]
fixed by #2490
