### ISSUE TITLE
[Bug Report] @formily/next.  TreeSelect 选择根节点时，开发环境报错

### ISSUE THREAD

**Issue by Z8264** [alibaba/formily#2534]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lively-cookies-hngyj?file=/src/App.js)

### Steps to reproduce
TreeSelect 组件

首次操作选择根节点

![image](https://user-images.githubusercontent.com/7948534/144007332-982f6cbb-06e8-4838-aaa5-5463b583dee2.png)

### What is expected?
无校验警告报错信息

### What is actually happening?
控制台报错
![image](https://user-images.githubusercontent.com/7948534/144007157-da14e2ce-ec9c-46d2-938c-1696e2c602aa.png)

### Package
@formily/next@2.0.2

---

**Comment by janryWang** [comment]
https://codesandbox.io/s/peaceful-elbakyan-6ri42?file=/src/App.js 

能不能先排除fusion的bug再提？

**Comment by Z8264** [comment]
@janryWang  提交bug前已经确认了Fusion在开发环境没有相关问题。
报错信息难道不是formiliy传给fusion错误类型导致的吗？

**Comment by janryWang** [comment]
你看我上面发的codesandbox，没有formily，也报错

**Comment by Z8264** [comment]
我截图信息，是prop value报错，其他报错事codesandbox环境问题

**Comment by janryWang** [comment]
![image](https://user-images.githubusercontent.com/4060976/144009314-d840268e-d6c2-47a4-89ee-d2045ab6347e.png)
这错不是一样的吗

**Comment by Z8264** [comment]
sorry，我验证方式应该有问题。
