### ISSUE TITLE
[Bug Report] 表单设计器自增表格默认数据配置

### ISSUE THREAD

**Issue by huaxiangsirenbutong** [alibaba/formily#2538]
#- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/designable)

### Steps to reproduce
我想在自增表格这块配置几条默认数据，对应表头key配置了，响应器也配置了数据源，可是到了前台JSON Schem解析后 后台配置的表格数据还是没显示，请问下需要怎么配置？

### What is expected?
前台可以正常显示表格数据

### What is actually happening?
没有正常显示

### Package
@formily/antd@2.0.0-rc.15‘

![image](https://user-images.githubusercontent.com/37055241/144162667-c10ffa13-4d9a-4f88-9e7c-4fb8b61f7582.png)

![image](https://user-images.githubusercontent.com/37055241/144162695-1dc84cd5-7f66-4094-8e99-10b64d7308be.png)
@cncolder 
---

**Comment by yexianli** [comment]
请问一下你解决了这个问题了吗？
