### ISSUE TITLE
[Bug Report] Input组件的addonAfter为Field时，引发的莫名其妙的bug

### ISSUE THREAD

**Issue by henryzp** [alibaba/formily#2567]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/broken-bird-6fjp7?file=/EditTable.tsx)

### Steps to reproduce
1. 当前已经有一个了，新增一个
2. 尝试删除第一个

### What is expected?
新增一个，能正常删除其他的，而不是非要从最后一个开始删

### What is actually happening?
1. 当前已经有一个了，新增一个
2. 尝试删除第一个，没法删除（但删除新增的一个，是没问题的，即从下往上删，是ok的）
3. 另外在做选择切换的时候，会发生混乱（删除某一个后）

### Package
@formily/antd@2.0.3

所有的版本都用的是2.0.3

---

**Comment by janryWang** [comment]
basePath不应该设置空，因为你是挂在ArrayTable的，必须把路径挂在它的父亲节点，`array.0`这样的节点上

**Comment by henryzp** [comment]
@janryWang ，不对啊。。。我这个addonAfter属性和外层的是平行的两个字段。。

我把第一个的basePath不设置空了，第二个设置为空，还是一样的问题，就是添加多个，上面的没法删除

当然解决的方式不是没有，要写成两个Field，而不是挂载到addonAfter下面去，但这样得重写样式了

**Comment by janryWang** [comment]
你说的外层平行总不会跟ArrayTable这个字段平行吧，如果是的话，那就会出现多个name一样的字段挂在顶层，你自己好好捋一捋这个关系，建议用chrome devtools看看结构

**Comment by henryzp** [comment]
我看了呀，如果外层的结构叫array

input的字段叫a，它旁边的下拉是叫b，我希望的结构是：

array: [ { a: 1, b: 2 } ]，而不是b在a的结构下面，我用devtools看过结构了。。如果第二个select不加basepath，那么会变成object的结构了

**Comment by janryWang** [comment]
可以实现个自定义组件，这样你的basePath可以基于useIndex拿到的索引来拼路径
