### ISSUE TITLE
[Feature Request] schema属性扩展

### ISSUE THREAD

**Issue by lin616386** [alibaba/formily#2581]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义扩展schema，扩展更灵活的属性配置以及解析

### What does the proposed API look like?
全局注册schema冗余属性，以及对应的transformToField方法

**Comment by janryWang** [comment]
本身就支持的
