### ISSUE TITLE
[Feature Request] schama自定义字段并自定义解析

### ISSUE THREAD

**Issue by lin616386** [alibaba/formily#2583]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
****场景描述****

在setting-form中**自定义数据源配置组件**，支持界面化配置api以及自定义数据源两种方式，并将这个结果存放在schema的json中。目前结构定义了，但是没有途径在编辑态动态解析出已经配置的数据源。预览态中，需要在schemaField中配置的数据源解析成field的dataSource进行显示。

**实现路径**

我在creatResource中，生成的schema增加一个属性optionBinder,其中包含内容为数据源的不同来源和配置，比如：

`optionBInders: {enum:[{label:"女“, value:"femal"}]}`

但是目前不知组件拖拽到workspace时，如何直接解析出optionBinder中enum的配置数据源。查看源码@formily/json-schema的transformer方法，获取dataSource的路径是固定写死的，不知怎么去扩展解析这个数据源。不知这种场景是否支持？

### What does the proposed API look like?
希望全局注册shischema字段并配置相应的解析逻辑，在编辑态也能够响应该配置。

**Comment by janryWang** [comment]
Schema.registerPatches是可以实现自定义属性解析的
