### ISSUE TITLE
[Feature Request] formily 2.0 官网加载不出来、太慢问题

### ISSUE THREAD

**Issue by WuHuSa** [alibaba/formily#2624]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

解决问题：用户查询文档方便，用户才能方便使用做业务开发啊

无意中了解到 formily 表单方案，很赞o(￣▽￣)ｄ，不过 v2 的文档总是出现打不开的情况，还有周边生态比如 @formily/antd，就一直打不开，最近总出现这个情况。。。后续想用此组件开发总查不到文档没法用了~

### What does the proposed API look like?
期望：能像 antd 官网一样一点就开

**Comment by janryWang** [comment]
去disucssion里讨论吧 https://github.com/alibaba/formily/discussions
