### ISSUE TITLE
[Bug Report] 在safari中，FormGrid 报错。ReferenceError: Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by dengxianMo** [alibaba/formily#2628]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oxvk2)

### Steps to reproduce
在safari中打开链接

### What is expected?
在safari中，正常展示

### What is actually happening?
页面报错，不展示

### Package
@formily/antd@2.0.5

---

**Comment by dengxianMo** [comment]
safari version 13.0.5

**Comment by dengxianMo** [comment]
formily/antd@2.0.0-rc.15  以及之前的都可以

**Comment by janryWang** [comment]
Safari是支持css grid的吗
