### ISSUE TITLE
[Bug Report] schema 里的 default 值会覆盖原来的空字符串

### ISSUE THREAD

**Issue by Jiazhi-Wong** [alibaba/formily#2629]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/schemade-defaulthui-fu-gai-kong-zhi-0kcu1?file=/App.tsx)

### Steps to reproduce
demo直接重现

### What is expected?
form.values.input 保持空字符串

### What is actually happening?
form.values.input 的值为"默认值"

### Package
@formily/react@2.0.5

---

1、input字段会有一个默认值，如schema所见
2、第一次表单编辑的时候，运营把默认值清掉，点了保存
3、所以重新编辑的时候，input字段就是空字符串了，但是这时formily用default值覆盖了原有的空字符串

请问这种场景怎么避免空字符串被覆盖？

**Comment by janryWang** [comment]
需求不合理，如果值为空，必然会走到默认值逻辑里去
