### ISSUE TITLE
[Bug Report] asterisk for FormItem is not working

### ISSUE THREAD

**Issue by jymsy** [alibaba/formily#2635]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wandering-wildflower-u9u0s?file=/App.tsx)

### Steps to reproduce
code as in codesandbox, it is ok in 2.0.3

### What is expected?
asterisk is not shown

### What is actually happening?
asterisk is shown

### Package
@formily/antd@2.0.5

---

**Comment by jymsy** [comment]
![image](https://user-images.githubusercontent.com/2777671/146340727-a780304e-fc6f-4812-b775-d781ef4329c3.png)

**Comment by janryWang** [comment]
不是bug，是feature，正常用法如果指定了required为true，一定会出星号

**Comment by jymsy** [comment]
@janryWang 那之前2.0.3的时候向上面那么写星号可以隐藏是bug？现在这是修复了么？

**Comment by jymsy** [comment]
@janryWang 
![image](https://user-images.githubusercontent.com/2777671/146474614-2a94bd30-59ee-4cdd-ae4c-0eaa8d4e3e8d.png)

**Comment by xmsz** [comment]
有解决方案了吗
