### ISSUE TITLE
[Bug Report] 相对路径计算并不支持在数据路径基础上做计算

### ISSUE THREAD

**Issue by LouisaNikita** [alibaba/formily#2643]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/void-xiang-dui-lu-jing-3wehw?file=/App.tsx)

### Steps to reproduce
如示例中的 修改就保存2

### What is expected?
void不占路径计算，可以如 “修改就保存1”的写法使用

### What is actually happening?
相对路径计算中，void在一定条件下占路径计算

### Package
@formily/core@2.0.6

---

**Comment by janryWang** [comment]
想了想，相对路径其实不属于标准用法，最近刚给formily协议支持了$index $record $self.index $self.indexes来读数组内数据，这种用法更简单，也更容易理解，所以未来可能会把相对路径能力干掉，所以这个bug先不修复吧
