### ISSUE TITLE
[Bug Report] 设计器bug，点击出码按钮（json,代码块）报错

### ISSUE THREAD

**Issue by Ddddaemon** [alibaba/formily#2647]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/alibaba/formily/security)

### Steps to reproduce
无痕打开https://designable-antd.formilyjs.org/
随便拖拽几个组件，点击出码按钮（json/代码块)，报依赖错误

### What is expected?
能用

### What is actually happening?
cdn 依赖错误

### Package
@formily/react@1.0.0

---

**Comment by janryWang** [comment]
cdn服务挂了，等恢复吧，还有designable相关的bug，最好还是去 https://github.com/alibaba/designable/issues 上面提吧
