### ISSUE TITLE
[Bug Report] 更改 componentProps 无法触发 effect

### ISSUE THREAD

**Issue by StarHosea** [alibaba/formily#2654]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-williams-jpj1x?file=/App.tsx)

### Steps to reproduce
1. 点击提交按钮
2. effect 应该触发，日志中应该打印 "props changed"

### What is expected?
1. 点击提交按钮
2. effect 应该触发，日志中应该打印 "props changed"

### What is actually happening?
1. 点击提交按钮
2. effect 未触发

### Package
@formily/core@2.0.6

---

**Comment by janryWang** [comment]
reactive机制需要理解清楚，componentProps是个对象，它内部属性变化是不会触发componentProps自身变化事件的，你可以用onFieldReact，然后调用componentProps的toJS来触发整体依赖收集实现内部任意属性变化的触发，也可以包一个
```
import { observe } from '@formily/reactive'

const onFieldComponentPropsChange = (pattern,callback)=>{
  const disposes = []
  onFieldInit(pattern,(field)=>{
      disposes.push(observe(field.componentProps,callback))
  })
  onFormUnmount(()=>{
    disposes.forEach(fn=>fn())
  })
}

```
