### ISSUE TITLE
[Bug Report] schema properties path 解析

### ISSUE THREAD

**Issue by vladimirdh** [alibaba/formily#2669]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-wind-o1ojv?file=/App.tsx)

### Steps to reproduce
初始渲染时已经复现，`test1:after`变成了`test1`

### What is expected?
{
  "test1:after": "value",
  "test2": 1,
  "alias": 1
}

### What is actually happening?
{
  "test1": "value",
  "test2": 1,
  "alias": 1
}

### Package
@formily/path@2.0.6

---

看起来像是被解析成解构的用法了，不清楚具体背景，找了下官网也没找到相关的文档
https://github.com/alibaba/formily/blob/formily_next/packages/path/src/tokens.ts#L110

**Comment by janryWang** [comment]
:是保留字符，你可以加`\\:`转义
