### ISSUE TITLE
[Bug Report] Element的ArrayItems的items包裹两层void，值却返回对象

### ISSUE THREAD

**Issue by lp0124** [alibaba/formily#2671]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-chaum-52z1u?file=/src/App.vue)

### Steps to reproduce
添加条目 - 提交

### What is expected?
`{
  string_array: [
    11,
    22,
    33
  ]
}`

### What is actually happening?
`{
  string_array: [
    {
      input: 11
    },
    {
      input: 22
    },
    {
      input: 33
    }
  ]
}`

### Package
@formily/element@2.0.6

---

**Comment by henryzp** [comment]
看了你的写法，按照我对formily的理解，它的结果就是`{ string_array: [ { input: 11 }, { input: 22 }, { input: 33 } ] }`这样的。。

然后如果你的后端结构是那样的话，需要自己处理一下结果，或者看看formily的解构那一块，看看能不能达到你的需求
