### ISSUE TITLE
[Bug Report] 使用官方自增列表例子 在本地运行报错

### ISSUE THREAD

**Issue by TaylorWizard** [alibaba/formily#2700]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-colden-lc1et?file=/src/App.vue)

### Steps to reproduce
本地运行 

1. 点击add
2. 文本框输入
3. 再次点击add 就会报如下的错
![](https://picasso-static.xiaohongshu.com/fe-platform/813db32056c4aa3fa7dc5a8f06ef9580ed6b4a0e.png)

### What is expected?
不报错正常使用

### What is actually happening?
报错不能正常使用

### Package
@formily/reactive-vue@2.0.7

---

**Comment by janryWang** [comment]
codesandbox能不能复现
