### ISSUE TITLE
[Feature Request] @formily/antd@latest ArrayItems receive empty array by default

### ISSUE THREAD

**Issue by skyfore** [alibaba/formily#2732]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes ArrayItems is **not required**, but we receive **empty array such as []** by default。

很多时候业务中的 ArrayItem 不全是 **必填**，但是在提交时默认返回了空数组，正常期望的行为是不提交任何数据。

### What does the proposed API look like?
ArrayItem 当在提交时没有子项不给任何值

**Comment by skyfore** [comment]
https://antd.formilyjs.org/components/array-items 文档站实例可以直接点提交看到 console 中的值，可复现问题

**Comment by janryWang** [comment]
这个是feature，ArrayField会默认带上空数组，保证自定义组件不会因为空值挂掉，如果业务上不希望提交，自己做过滤吧

**Comment by skyfore** [comment]
这个做过滤成本可能有点高吧。。。我们是动态下发表单，不可能明确知道哪些是 List，有没有可能比如 List 的配置中增加默认不提交空数组的逻辑呢，或者 submit 有没有一些 hook 可以提供给用户能够快速根据字段相关模型过滤数据？
