### ISSUE TITLE
[Bug Report] vue Schema 片段联动功能 type 从 object 切换成 array 时无法正常渲染

### ISSUE THREAD

**Issue by xn330125** [alibaba/formily#2740]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-spence-f2z64?file=/src/App.vue)

### Steps to reproduce

1. schema1 type 是 object
2. schema2 type 是 array
3. schema1 替换成 schema2 

```
const schema1 = {
  type: "object",
  properties: {
    input1: {
      type: "string",
      "x-component": "Input",
      "x-decorator": "FormItem",
      title: "test1",
    },
  },
}

const schema2 = {
  type: "array",
  "x-component": "ArrayCollapse",
  "x-decorator": "FormItem",
}
```

### What is expected?
type 不同时也能正常渲染

### What is actually happening?
schema1 替换成 schema2 时， 数组组件无法渲染

如果类型都是 object ，替换后渲染正常

### Package
@formily/vue@2.0.8

---

**Comment by janryWang** [comment]
@MisicDemone 麻烦看看这个问题
