### ISSUE TITLE
[Bug Report] Input输入框在editable为false的情况下，传入的值显示N/A

### ISSUE THREAD

**Issue by XcGuaN-miepia** [alibaba/formily#2749]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/XcGuaN-miepia/formily-antdv-input)

### Steps to reproduce
form中的editable设为false，在mounted当中使用setValues传入值

### What is expected?
input组件在editable为false的情况下显示对应传入的值

### What is actually happening?
目前显示为N/A

### Package
@formily/antdv@1.0.0

---

**Comment by janryWang** [comment]
PreviewText.Placeholder可以配置

**Comment by XcGuaN-miepia** [comment]
> PreviewText.Placeholder可以配置

不是默认显示的问题，是我用JSON Schema传入进去，没有设置default值，在createForm将editable设为false，这时候为只读。之后调用setValues方法传值进去，对于select组件能够显示新传进去的值，但是Input组件不支持，还是显示为N/A

**Comment by zhouxinyong** [comment]
已修复 @janryWang @XcGuaN-miepia
