### ISSUE TITLE
[Bug Report] 使用 concat 生成的 FormPath，通配符无法匹配路径

### ISSUE THREAD

**Issue by xn330125** [alibaba/formily#2752]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-morse-e3ume)

### Steps to reproduce
使用 concat 生成的 带通配符 * 的路径，无法正确匹配

```js

console.log(FormPath.parse('a.*').match('a.b')) // true

console.log(FormPath.parse('a').concat('*').match('a.b')) // false

```

### What is expected?
`FormPath.parse('a').concat('*')` 生成的路径应该和 `FormPath.parse('a.*')` 等价

### What is actually happening?
`FormPath.parse('a').concat('*')` 生成的路径没有通配符的效果
其中 `isMatchPattern === false`
### Package
@formily/path@2.0.8

---

**Comment by janryWang** [comment]
concat只适用于数据操作路径，不适用于匹配型路径，所以建议走字符串模板拼接
