### ISSUE TITLE
[Bug Report] @formily/next 的 ArrayItems.SortHandle 不支持自定义样式和类名

### ISSUE THREAD

**Issue by Rebugmon** [alibaba/formily#2753]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-forest-g46xl?file=/App.tsx)

### Steps to reproduce
查看上面 Codesandbox

### What is expected?
ArrayItems.SortHandle 的自定义样式和类名能生效

### What is actually happening?
ArrayItems.SortHandle 的自定义样式和类名不生效

### Package
@formily/next@2.0.8

---

ArrayItems.Remove 和 ArrayItems.Addition 是没问题的

**Comment by janryWang** [comment]
目前fusion的SortHandle没实现拖拽功能，暂时没打算实现
