### ISSUE TITLE
can't use with next.js 无法与next一起工作

### ISSUE THREAD

**Issue by hohogpb** [alibaba/formily#2766]
event - compiled client and server successfully in 252 ms (638 modules)
wait  - compiling...
**_error - ./node_modules/@formily/next/esm/array-base/main.scss
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@formily\next\esm\style.js_**

**Comment by ChenAlmost** [comment]
@hohogpb hello, do you solve this problem?

**Comment by 0fan** [comment]
+1
2022年11月06日19:58:01

**Comment by hohogpb** [comment]
> @hohogpb hello, do you solve this problem?

no~ i think this is a problem may not be solve in short future~

**Comment by mengliuliu** [comment]
我也遇到这样的问题了，是不兼容么

**Comment by HUANGXUANKUN** [comment]
+1

**Comment by laogui** [comment]
+1

**Comment by franckXu** [comment]
+1
