### ISSUE TITLE
[Bug Report] Element 的 ArrayTable 点击新增行报错

### ISSUE THREAD

**Issue by Hansuku** [alibaba/formily#2779]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-fast-0ogqm?file=/package.json)

### Steps to reproduce
只要使用[官网 codesandbox ](https://element.formilyjs.org/guide/array-table.html#json-schema-%E6%A1%88%E4%BE%8B) 然后去点一下 fork 就可以复现
比较神奇的是官网本身的 codesandbox 是可以正常运行的 但是随便 fork 一份下来就不正常了 通过排查发现getArrayTableColumns这个函数在可运行版本和不可运行版本是不一致的 但是看了下依赖都是一样的

### What is expected?
能够正常新增行

### What is actually happening?
新增行报错

### Package
@formily/element@2.0.8

---

**Comment by janryWang** [comment]
最新分支代码已经修复了，等发版
