### ISSUE TITLE
[Bug Report] Select组件通过异步加载过来的数据只读显示的是值

### ISSUE THREAD

**Issue by XcGuaN-miepia** [alibaba/formily#2790]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-grass-7pmr1?file=/src/App.vue)

### Steps to reproduce
form属性{ editable: false }，select组件的JSON Schema没有填写Enum属性，DataSource通过异步获取，给select设置默认值 ccc

### What is expected?
显示的值为 BBB

### What is actually happening?
显示的值为 ccc

### Package
@formily/antdv@1.0.0

---

如果改为同步，enum当中填写值可以显示正常值

**Comment by zhouxinyong** [comment]
这是Select preview的bug 我修一下
