### ISSUE TITLE
[Bug Report] 在 x-reactions 里面使用 dataSource[0].disabled 来更新组件状态，内部状态已更新，但是没触发视图更新

### ISSUE THREAD

**Issue by crown3** [alibaba/formily#2793]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-matsumoto-h6pi1?file=/App.tsx)

### Steps to reproduce
1. 打开 codesandbox 后，选项1处于 disbaled 态，符合预期

2. 在输入框输入 123 后，radio 的 title 以及 required 状态均已更新，但是 disabled 状态没更新，不符合预期

3. 此时点击 选项2，来手动触发视图更新，此时 选项1 将不再处于 disabled，此时 radio 的 disabled 才符合预期

### What is expected?
在步骤 2 时，radio 的 disabled 状态能正确更新，而不用进行步骤 3 来进行手动更新

### What is actually happening?
请查看重现步骤部分

### Package
@formily/react@2.0.9

---

**Comment by janryWang** [comment]
dataSource字段目前是浅响应数据，主要是为了性能优化，考虑到dataSource数据量很可能会非常大，所以你要更新的话，请用map
