### ISSUE TITLE
[Bug Report] x-component-props 中的对象属性地址引用会被改变

### ISSUE THREAD

**Issue by whj1995** [alibaba/formily#2794]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/staging-snow-d4v6g?file=/App.tsx)

### Steps to reproduce
如codesandbox，对象属性会发生突变

### Package
@formily/react@2.0.9

---

**Comment by janryWang** [comment]
你如果想使用原始引用，可以用useField来拿，目前默认是在每次渲染的时候对component-props做toJS传给组件，主要是为了触发深度依赖收集
