### ISSUE TITLE
[Bug Report] ssr error

### ISSUE THREAD

**Issue by ZeroJsus** [alibaba/formily#2799]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
![image](https://user-images.githubusercontent.com/19191127/151400311-4de8007b-dad3-4179-84f6-7737947ef7dc.png)

### Steps to reproduce
Error when use ssr render

### What is expected?
Unexpected token '.'

### What is actually happening?
Unexpected token '.'

### Package
@formily/json-schema@2.0.9

---

**Comment by janryWang** [comment]
这是因为表达式用到了es最新语法，node不支持

**Comment by ZeroJsus** [comment]
> 这是因为表达式用到了es最新语法，node不支持

就是我的事件实现里面用到了 最新语法？有没有什么办法可以让node支持呢

**Comment by janryWang** [comment]
升级node版本
