### ISSUE TITLE
[Bug Report] antd 的 TreeSelect 组件在 readPretty 模式下取数据源时使用了错误的 props 属性

### ISSUE THREAD

**Issue by maoqxxmm** [alibaba/formily#2848]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/nice-maxwell-1hz21l?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
使用 TreeSelect 的 treeData 属性传入选项，传入初始值，在 readPretty 模式下查看。

### What is expected?
应该读取 TreeSelect 的 treeData 以及 treeNodeLabelProp 2 个属性，得到实际需要展示的值

### What is actually happening?
Preview.TreeSelect 组件直接读取了 dataSource 及 props.options，而 TreeSelect 实际使用的是 treeData

### Package
@formily/antd@2.0.12

---

**Comment by janryWang** [comment]
来个PR？

**Comment by maoqxxmm** [comment]
> 来个PR？

等我忙完手上这个项目😭
