### ISSUE TITLE
[Feature Request] 表单支持非编辑模式下强制校验

### ISSUE THREAD

**Issue by StarHosea** [alibaba/formily#2890]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求场景中，表单处于非编辑模式，用户点击提交仍然需要校验表单内容，有错误的话切换到编辑模式，提示用户修改

### What does the proposed API look like?
form.validateForce( pattern)

**Comment by janryWang** [comment]
为什么只读态还要校验，只读态都是直接拿的后端数据了，后端数据本身肯定是合法数据，如果不合法，那是后端自己的问题

**Comment by StarHosea** [comment]
需求中，用户数据可以暂存（不校验），暂存后下次打开进入查看模式，此时可以直接提交（需校验）。

**Comment by semmywong** [comment]
确实有这种需求场景，比如input是readOnly，用户不能手动输入，只能点击查找从另外一个页面查找回调回显回来，
![image](https://user-images.githubusercontent.com/67748948/159398280-f0e49f4e-4710-4ec3-a717-cb5fe4d55c34.png)
但是目前batchValidate和validateSelf这边 设定了只能`editable`才进行校验，这样就不符合场景需求了。
![image](https://user-images.githubusercontent.com/67748948/159398474-16dd7159-5d1b-4575-8044-219846bd7076.png)
![image](https://user-images.githubusercontent.com/67748948/159398906-7db3a6d3-ae4e-453c-b041-b51c8e886a97.png)

**Comment by janryWang** [comment]
@semmywong 那你就不应该用Input组件，直接用PreviewText.Input，然后不要设置阅读态
