### ISSUE TITLE
[Feature Request] FormDialog

### ISSUE THREAD

**Issue by Zwahxf** [alibaba/formily#2933]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
FormDialog 如何设置弹出的modal的宽呢

### What does the proposed API look like?
FormDialog 如何设置弹出的modal的宽呢

**Comment by Zwahxf** [comment]
@janryWang 问题怎么关了呢

**Comment by janryWang** [comment]
提问去discussion里提
