### ISSUE TITLE
[Bug Report] Cascader 阅读态组件显示错误

### ISSUE THREAD

**Issue by sogud** [alibaba/formily#2935]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-ritchie-zx7pff?file=/App.tsx)

### Steps to reproduce
在有children时获取阅读态数据时显示字段过多，应该只显示最后一项。

### What is expected?
应该只显示最后一项。

### What is actually happening?
所有路径都显示了。

### Package
@formily/antd@2.0.15

---

看了源码，getLabels那个函数有问题。

**Comment by janryWang** [comment]
目前设计就是要显示路径的，显示路径具体存在什么问题
