### ISSUE TITLE
[Bug Report] @formily/antd@2不支持4.6.3及以下版本的antd4

### ISSUE THREAD

**Issue by VinVC** [alibaba/formily#2946]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-dust-ugnzrq)

### Steps to reproduce
安装4.6.3及其以下的antd4

### What is expected?
@formily/antd@^2.0.0可以支持antd@^4.0.0

### What is actually happening?
使用ant@4~ant@4.6.3就会报错

### Package
@formily/antd@2.0.15

---

https://github.com/ant-design/ant-design/pull/26705

**Comment by janryWang** [comment]
示例formily版本不对，不是2.0.0-beta的

**Comment by VinVC** [comment]
> 示例formily版本不对，不是2.0.0-beta的

将实例中的@formily/x的所有版本都调整到最新了，依然会报错。原因是@formily/antd2使用了antd在4.6.4才暴露的接口ConfigProvider.ConfigContext
