### ISSUE TITLE
[Bug Report] 基于官方Upload组件写法，提交时无法获取值

### ISSUE THREAD

**Issue by zhonglijun** [alibaba/formily#2949]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/idqkcw?file=/src/App.vue)

### Steps to reproduce
点击上传=>点击提交=>无上传数据

### What is expected?
希望能够正常上传  提交时能获取上传数据  回显时正常回显

### What is actually happening?
无法正常获取数据 回显

### Package
formily-antdv@1.0.0

---

**Comment by zhouxinyong** [comment]
正在修复中

**Comment by zhouxinyong** [comment]
已修复
