### ISSUE TITLE
[Bug Report] define定义领域模型，指定方法为action无效

### ISSUE THREAD

**Issue by necromancer1** [alibaba/formily#2953]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/broken-cloud-9sq8h5?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
在手动定义领域模型后：

`
import { observable, define, action } from "@formily/reactive";

class Page {
  value = 3;

  constructor() {
    this.makeObservable();
  }
  makeObservable() {
    define(this, {
      value: observable.ref,
      getGrids: action
    });
  }
  getGrids() {
    this.values = this.values + 1;
    return this.value;
  }
}

export default Page;
`

在它处更改了value值，getGrids()方法调用后返回的value无变化。

### What is expected?
见例子

### What is actually happening?
见例子

### Package
@formily/reactive@2.0.15

---

经测试，在v2.0.0-beta.80不存此问题，在v2.0.0以后版本均有此问题。

**Comment by janryWang** [comment]
action什么无效？预期是什么？麻烦完善清楚问题，codesandbox给出具体可复现代码

**Comment by necromancer1** [comment]
[例子](https://codesandbox.io/embed/frosty-faraday-rzj5qt?fontsize=14&hidenavigation=1&theme=dark)

**Comment by janryWang** [comment]
action在新版中是强制不收集依赖了的，这里需要注意
