### ISSUE TITLE
[Bug Report] Upload组件回显不了

### ISSUE THREAD

**Issue by zhonglijun** [alibaba/formily#2954]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/b04gou?file=/src/App.vue)

### Steps to reproduce
引用的便是官网demo源代码，（action改成上传地址，接口成功返回）点击上传后 无回显 提交时无数据

### What is expected?
上传后 正常显示，提交时 能获取附件值

### What is actually happening?
点击上传后 无回显 提交时无数据

### Package
formily-antdv@1.0.0

---

**Comment by zhouxinyong** [comment]
正在修复中

**Comment by zhouxinyong** [comment]
已修复
