### ISSUE TITLE
[Bug Report] 通过setComponentProps 方法修改 dataSource 属性不生效

### ISSUE THREAD

**Issue by ibeizhu** [alibaba/formily#3018]
- [ ] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-kilby-o4k7dg?file=/App.tsx)

### Steps to reproduce
1、schema 携带 enum 数据源
2、通过setComponentProps 方法修改 dataSource 属性
3、结果数据源没有更新，期望能更新

### What is expected?
期望能通过setComponentProps 方法修改 dataSource 属性生效

### What is actually happening?
通过setComponentProps 方法修改 dataSource 属性不生效

### Package
@formily/shared@2.0.18

---

看代码，应该是 mapProps 的逻辑有问题

https://github.com/alibaba/formily/blob/formily_next/packages/react/src/shared/connect.ts#L22

**Comment by coolbob1998** [comment]
* 你通过 setComponentProps 改变的是组件的属性
* dataSource 是字段的属性，不是组件的属性。

**Comment by janryWang** [comment]
这个问题是在组件connect的时候只映射了字段模型的dataSource，没想过还要以组件属性为兜底，现在把这个优先级加上的话，对线上用户影响会比较大，比如用户之前在组件props上设置了dataSource，发现没生效，然后改成enum，然后忘记把之前的代码删了，升级新版会导致enum设置的dataSource失效
