### ISSUE TITLE
Formily文档大纲

### ISSUE THREAD

**Issue by janryWang** [alibaba/formily#623]
考虑到很多用户反馈文档实在太不友好，在这里专门提一个Issue，方便用户一起对文档的结构做review，现在先大概理一下文档提纲，大家先看看，有啥意见的可以提哈。还有就是，如果想认领文档一部分的，也可以提出来，一起贡献，一起完善，感谢大家！

- 首页
  - 更快速
  - 更高效
  - 更完备
- JSON/JSX Schema驱动开发
  - 介绍
    - JSON/JSX Schema不同开发模式的差异
    - @formily/antd/next的定位于作用
  - 快速开始
    - 以一个实际表单页面开发为视角，分步引导开发，引导至后面的各种文档(可以加一个视频教程)
  - 开发准备
    - 环境&安装&配置
    - 理解表单协议
    - 理解SchemaForm组件
    - 理解SchemaMarkupFIeld组件
    - 理解表单生命周期
    - 理解actions/effects
    - 理解表单路径系统
    - 理解value/values/initialValue/initialValues的区别
    - 理解表单节点树Field&VirtualField
    - 理解表单组件扩展机制
  - 实践教程
    - 使用@formily/antd
    - 使用@formily/next
    - 使用布局组件
    - 使用Effect Hooks
    - 自定义Effect Hook
    - 借助Rxjs实现联动逻辑
    - 跨组件操作表单
    - 跨组件消费表单生命周期
    - 管理业务逻辑
    - 定制校验规则
  - 进阶教程
    - 如何实现递归渲染组件
    - 如何实现自增列表组件
    - 如何开发自定义组件
    - 如何接入组件库
    - 如何开发布局组件
    - 如何开发超复杂自定义组件
  - FAQ
- JSX驱动开发
  - 介绍
    - 纯JSX驱动开发与JSON Schema开发的差异
    - @fomily/react的定位于作用
  - 快速开始
    - 以一个实际表单页面开发为视角，分步引导开发，引导至后面的各种文档(可以加一个视频教程)
  - 开发准备
    - 环境&安装&配置
    - 理解Form组件
    - 理解FormItem组件
    - 理解@formily/react
    - 理解表单生命周期
    - 理解actions/effects
    - 理解表单路径系统
    - 理解value/values/initialValue/initialValues的区别
    - 理解表单节点树Field&VirtualField
  - 实践教程
    - 如何使用@formily/antd
    - 如何使用@formily/next
    - 使用Effect Hooks
    - 自定义Effect Hook
    - 借助Rxjs实现联动逻辑
    - 跨组件操作表单
    - 跨组件消费表单生命周期
    - 管理业务逻辑
    - 定制校验规则
  - 进阶教程
    - 如何实现自增列表组件
    - 如何接入组件库
  - FAQ
- 底层扩展开发
  - 介绍
    - @formily/core在整个表单解决方案的定位与作用
  - 入门教程
    - 理解@formily/core核心API
    - 理解Observable Graph
  - 实践教程
    - 如何实现一个@formily/vue
    - 如何实现一个@formily/mini-app(支付宝小程序)
  - FAQ
- 升级迁移指南
  - uform迁移formily
- 开发调试指南
  - devtools
- 贡献指南
  - 如何理解源码
  - 如何提Issue(Bug/Feature)
  - 如何提PR
  - 如何提问题
  - 如何捐赠
- API手册
  - @formily/antd
  - @formily/next
  - @formily/mobile
  - @formily/react
  - @formily/core

**Comment by seawenzhu** [comment]
如何集成vue组件库

**Comment by janryWang** [comment]
> 如何集成vue组件库

集成vue这块，暂时不考虑，更多的是提供接入教程

**Comment by TopJohn** [comment]
文档大概什么时候可以开放

**Comment by bow3nwang** [comment]
请问下怎么认领呢，使用了一段时间 可以帮助编写一部分文档

**Comment by janryWang** [comment]
> 请问下怎么认领呢，使用了一段时间 可以帮助编写一部分文档

你觉得哪部分感兴趣，就直接认领吧，可以认领一篇文章，也可以认领多篇文章
