### ISSUE TITLE
不支持，AntD 4.x ，现在修改成 formily 代码是不是要统一更新呀？

### ISSUE THREAD

**Issue by alexPang6** [alibaba/formily#640]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Formily?
  - Did this work in previous versions of Formily?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
还在计划中，先等antd4发布正式版

**Comment by alexPang6** [comment]
谢谢。
