### ISSUE TITLE
[Bug]Input组件prefix属性失效，以前正常，更新后就没有了。

### ISSUE THREAD

**Issue by birdycn** [alibaba/formily#642]
uform表单校验中密码框存在prefix：
https://uformjs.org/#/YZCyCk/eWhbhpUWT8
![1](https://user-images.githubusercontent.com/32201961/74049889-0b6f5800-4a10-11ea-934f-d1a5d228ddf3.png)

uform-next中存在prefix属性但无法显示
https://uform-next.netlify.com/#/9NCgCJ/kEhrhET0T4
![image](https://user-images.githubusercontent.com/32201961/74082558-24bae780-4a96-11ea-8101-bd943ab260d8.png)

官方demo codesandbox：https://codesandbox.io/s/loin1，也无法显示prefix

本地项目原先是可以正常显示input组件中的prefix，后来更新了antd v4就无法显示，回退版本重新安装npm也不行，排查了一个晚上，实在无法定位问题，希望能够解决。

猜测是把之前版本的prefix也改了？

原先可以正常显示的代码
```
 <SchemaMarkupField type="string" name="username"
              x-component-props={{ prefix: <LegacyIcon type="user" />, placeholder: '用户名', size: 'large' }}
              x-rules={[{ name: '用户名', required: true, trim: true }]}
            />
```

**Comment by birdycn** [comment]
最早的版本通过prefix还可以显示图标的，后面更新就没了。但是suffix属性还可以，是不是prefix被占用了。能不能提供另一个代替的参数

**Comment by janryWang** [comment]
先不要升级antdv4，目前对v4没有做任何兼容处理

**Comment by birdycn** [comment]
> 先不要升级antdv4，目前对v4没有做任何兼容处理

已经回退到老版本了，也不行。然后用codesanbox复现，直接用官网的demo代码，发现antd3.x 也是不行，但是suffix属性却正常。

自定义组件发现prefix属性传不进去（应该是register之前被提取了，我看了其他的代码有prefix作为classname前缀）

这是codesanbox地址:https://codesandbox.io/s/shy-surf-2jxns

烦请大佬看看。 @janryWang

**Comment by birdycn** [comment]
测试用registerFormField 自定义组件传入prefix，发现也无法传入，把prefix改成任意属性（prefix1）可以，所以prefix应该是被拦截了没有向子组件传参。

**Comment by birdycn** [comment]
> 先不要升级antdv4，目前对v4没有做任何兼容处理

![image](https://user-images.githubusercontent.com/32201961/74084076-1d033f00-4aa6-11ea-9b09-baa31a9fb1ac.png)
应该跟这段代码有关，不知道怎么修改package包 @janryWang
