### ISSUE TITLE
Formily has not been published to npm

### ISSUE THREAD

**Issue by yetone** [alibaba/formily#646]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

  - What is the current behavior?

    npm cannot install @formily/antd

    ![image](https://user-images.githubusercontent.com/1206493/74211588-7f895480-4ccb-11ea-9579-f899b30e64ad.png)

  - What is the expected behavior?

    Install formily successfully

**Comment by changhui3067** [comment]
Our team met the same issue! Want to know when will the formily published in npm. There're still @uform/xxx in npm yet.

**Comment by MR03web** [comment]
same question toady

**Comment by wfk007** [comment]
same question
