### ISSUE TITLE
@formily/react 下架了吗

### ISSUE THREAD

**Issue by yinjikai** [alibaba/formily#652]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Formily?
  - Did this work in previous versions of Formily?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
还没发布

**Comment by yinjikai** [comment]
恩恩   看到群里说了
