### ISSUE TITLE
react-schema-renderer的 “如何接入 Form/FormItem 组件” 文档例子跑不起来

### ISSUE THREAD

**Issue by laughing-pic-zhu** [alibaba/formily#674]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Performance

2. Describe your issue: 
   [文档问题](https://github.com/alibaba/formily/blob/master/packages/react-schema-renderer/README.zh-cn.md#%E5%A6%82%E4%BD%95%E6%8E%A5%E5%85%A5-formformitem-%E7%BB%84%E4%BB%B6 )
  - CompatFormComponent函数多了个）结尾
  - 单例注册方式那行少了个）结尾

**Comment by janryWang** [comment]
可以直接提PR修一下吧

**Comment by laughing-pic-zhu** [comment]
家里网络没法pr
