### ISSUE TITLE
uform 官网 SEO 较弱

### ISSUE THREAD

**Issue by monkindey** [alibaba/formily#68]
![image](https://user-images.githubusercontent.com/6913898/57785952-3a98b780-7765-11e9-9946-96aa0809903d.png)

搜索 uform effect 居然找不到，只能找到对应的 issue。

看看 React, 我搜索 `React Fragment`

![image](https://user-images.githubusercontent.com/6913898/57785929-3076b900-7765-11e9-962e-bb2f0cf1551e.png)

**Comment by javahuang** [comment]
咱俩是同一个🐶🐶吗？我的搜 uform 第一二个分别是官网和 github，不过今天我同事用百度竟然直接没有

**Comment by monkindey** [comment]
搜索 uform ，其实是可以搜索到的。但是主要 uform 的内容的话是搜索不到的， 比如你要搜索 uform effects 概念。

**Comment by janryWang** [comment]
已升级dumi
