### ISSUE TITLE
type=‘array’时的表单校验

### ISSUE THREAD

**Issue by gaoleiming** [alibaba/formily#684]
1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - 对type=‘array’表单进行校验，setFieldState的方式添加错误提示，需要出发回流，才能正确显示错误提示
  - setFieldState设置对应errors后，马上出发错误提示（表单框红色，文案提醒）
  -   "@uform/antd": "^1.0.0-rc.1",
  - 没有使用过其他版本

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
给个codesandbox
