### ISSUE TITLE
当 addonAfter 为 React.Node 且表单为非编辑状态时，显示出现错误

### ISSUE THREAD

**Issue by JerryLyu93** [alibaba/formily#697]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
- Bug

2. Describe your issue:
  - What is the current behavior?
     当 addonAfter 为 React.Node 且表单为非编辑状态时，显示出现错误
  - What is the expected behavior?
    当 addonAfter 为 React.Node 且表单为非编辑状态时，显示正常
  - Which versions of Formily?
   1.0.4
  - Did this work in previous versions of Formily?
   nope

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox.

https://codesandbox.io/s/objective-tree-gjjg0?fontsize=14&hidenavigation=1&theme=dark

**Comment by JerryLyu93** [comment]
我将尝试提交一个 PR 进行修复。如果你们已在修复，请回复我一下。

**Comment by janryWang** [comment]
提PR吧
