### ISSUE TITLE
[Question]  formily 与 uform 啥关系？

### ISSUE THREAD

**Issue by DelBlank** [alibaba/formily#704]
如题，从 uform 迁移到 formily 需要成本由多高，json schema 是否可复用，组件内部逻辑是否需要修改？
.

**Comment by janryWang** [comment]
https://formilyjs.org/#/OOUKU4/WbFRFRurs3 看看这个

**Comment by DelBlank** [comment]
@janryWang 内容白屏大佬

**Comment by janryWang** [comment]
https://formilyjs.org/#/bkT9TE/WbFRFRurs3 这个链接
