### ISSUE TITLE
请问uform，可以满足我这个场景吗？ 或者可以给我一些建议吗

### ISSUE THREAD

**Issue by JinJieTan** [alibaba/formily#709]
![image](https://user-images.githubusercontent.com/47209029/76325889-d150e900-6322-11ea-8e01-df657d91304d.png)

我在上面的导入json按钮中，输入一段json，然后传输到后端帮忙解析后，返回一个object给我，然后这个object可以嵌套。我想根据这个object生成一个树形嵌套的动态表单，内容就是上面的每一列。请问可以做到吗 uform？

**Comment by janryWang** [comment]
只要是json schema结构，给formily即可渲染表单，所以不明白你的问题点在哪里，疑惑点在哪里

**Comment by JinJieTan** [comment]
谢谢大佬这么晚还回我，我明天早上好好整理一下我的问题，麻烦你了。这个问题困扰了我好几天



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Janry <notifications@github.com&gt;
发送时间: 2020年3月10日 23:11
收件人: alibaba/formily <formily@noreply.github.com&gt;
抄送: Peter <453089136@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/formily] 请问uform，可以满足我这个场景吗？ 或者可以给我一些建议吗 (#709)




只要是json schema结构，给formily即可渲染表单，所以不明白你的问题点在哪里，疑惑点在哪里

**Comment by JinJieTan** [comment]
官网的实现递归渲染组件和实现超复杂的自定义组件  页面打不开

**Comment by janryWang** [comment]
还没写，耐心等待

**Comment by JinJieTan** [comment]
我把这个库都推荐给我们公司的人了，我现在就是要做一个动态的树形表单

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Janry <notifications@github.com&gt;
发送时间: 2020年3月11日 12:05
收件人: alibaba/formily <formily@noreply.github.com&gt;
抄送: Peter <453089136@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/formily] 请问uform，可以满足我这个场景吗？ 或者可以给我一些建议吗 (#709)

**Comment by JinJieTan** [comment]
这是我的需求，但是我在官网上没有看到合适的例子可以实现

![image](https://user-images.githubusercontent.com/47209029/76386667-051e2400-63a0-11ea-87fb-07ce1d24035c.png)

我目前把header query body response 用display控制，然后用了antd的动态表单方式，用promise.al方式去校验，获取他们的表单值，也可以动态导入json,然后插入新的带默认值的表单。但是这里有一点我没法实现，就是导入的json，可以嵌套。嵌套后是一颗树形结构，如果用uform的话，我该怎么做呢？ 可以给点意见吗

**Comment by janryWang** [comment]
还是没理解你的需求，你说的信息量很大，但也看不到问题点在哪里，到底是要解决校验问题，还是解决默认值问题，还是树型结构问题？

**Comment by JinJieTan** [comment]
主要是校验问题和值的获取问题，我现在是全部切换到原生dom操作了，很麻烦。。在react里面&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Janry"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上11:28
收件人:&nbsp;"alibaba/formily"<formily@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/formily] 请问uform，可以满足我这个场景吗？ 或者可以给我一些建议吗 (#709)





 
还是没理解你的需求，你说的信息量很大，但也看不到问题点在哪里，到底是要解决校验问题，还是解决默认值问题，还是树型结构问题？

**Comment by janryWang** [comment]
校验用actions.validate可以手动校验，获取值，用actions.getFieldState也能获取值

**Comment by JinJieTan** [comment]
不好意思


我在你们官网和github找了很久也没有看到树形表单生成和校验啊


我的数据格式是{name:"xxx",items:[{name:"xxx"},{name:"xxxx"}]}这样的，有相关案例或者链接可以给我一个嘛？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Janry"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 下午4:03
收件人:&nbsp;"alibaba/formily"<formily@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/formily] 请问uform，可以满足我这个场景吗？ 或者可以给我一些建议吗 (#709)





 
校验用actions.validate可以手动校验，获取值，用actions.getFieldState也能获取值
