### ISSUE TITLE
官网页面(https://uform-next.netlify.com/#/9NCgCJ/8RCMC5hMhY) bug 

### ISSUE THREAD

**Issue by xiamu14** [alibaba/formily#711]
1. 官网页面(https://uform-next.netlify.com/#/9NCgCJ/8RCMC5hMhY) bug 
2. bug 
react.development.js:401 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
![](http://static.ohcat.xyz/issue__jie-ping-2020-03-11-shang-wu-10-53-25-1583895224524.png)

**Comment by janryWang** [comment]
老版官网不推荐查看了，现在主要看formilyjs.org
