### ISSUE TITLE
Can VirtualField be locally registered

### ISSUE THREAD

**Issue by muxfe** [alibaba/formily#730]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Feature request

2. Describe your issue:

  - What is the current behavior?
    - VirtualField 只能全局注册
  - What is the expected behavior?
    - 既然 components 可以给表单实例仅局部注册组件，那么 VirtualField 是不是也可以局部注册，因为我们有一个场景是同时使用两个不同的 formily/<组件库>，会导致 VirtualField 的覆盖
  - Which versions of Formily?
    - latest
  - Did this work in previous versions of Formily?
    - No

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

Thanks.

**Comment by janryWang** [comment]
这个规范控制掉，不要重名就行
