### ISSUE TITLE
不要在Issue中提问，请到答疑群中提

### ISSUE THREAD

**Issue by janryWang** [alibaba/formily#735]
issue只负责提Bug/Feature Request，不负责答疑

![image](https://user-images.githubusercontent.com/4060976/77178613-43cf7f00-6b02-11ea-9b77-d3859ecfd488.png)

**Comment by it1011** [comment]
为什么要进群？
已解决的问题怎么记录，大家如何通过issue找到答案，

**Comment by janryWang** [comment]
> 为什么要进群？
> 已解决的问题怎么记录，大家如何通过issue找到答案，

先看文档，文档给不了帮助的，再到答疑群提问，如果该问题不是不经过大脑的弱智问题，而且还是很典型的问题，我们会在文档的FAQ中记录

**Comment by huangzep** [comment]
还有微信群二维码吗

**Comment by darkmice** [comment]
![$B$8IHX6HIP)T6YGL92HQHK](https://user-images.githubusercontent.com/1502088/87737885-b598aa80-c80e-11ea-81de-a34f4fff7a1e.gif)

**Comment by MaskHao** [comment]
群在哪？

**Comment by bytrix** [comment]
> > 为什么要进群？
> > 已解决的问题怎么记录，大家如何通过issue找到答案，
> 
> 先看文档，文档给不了帮助的，再到答疑群提问，如果该问题不是不经过大脑的低级问题，而且还是很典型的问题，我们会在文档的FAQ中记录

FAQ打开一片空白

**Comment by superhos** [comment]
官网的文档页面都挂了，还有在维护吗？

**Comment by RunningJimmy** [comment]
群二维码过期了
