### ISSUE TITLE
Make formily more compatible with React Native

### ISSUE THREAD

**Issue by chinesedfan** [alibaba/formily#751]
1. How would you tag this issue?

  - Feature request

2. Describe your issue:

  - What is the current behavior?

@formily/react-schema-renderer tries to create a portal by package `react-dom` to collect field schemas [here](https://github.com/alibaba/formily/blob/9d0f2196a80328c63aec775797f9f38775c8261c/packages/react-schema-renderer/src/components/SchemaMarkup.tsx#L60). I guessed the reason, and please correct me if I misunderstood something.

  - What is the expected behavior?

Do the same thing by another way without package `react-dom`, because in RN environments, we don't want to include it.

If you are not planning to support RN, can you give some suggestions to omit `react-dom`?

  - Which versions of Formily?

1.0.9.

  - Did this work in previous versions of Formily?

No.

**Comment by chinesedfan** [comment]
Also note that,

- RN uses `deepFreezeAndThrowOnMutationInDev.js` to freeze the component state.
- immer always returns `writable: true` for property descriptors.

If users call something like `mutators.change(state.xx)` twice, it may trigger a crash when developing.

- v1.1.x, Cannot both specify accessors and a value or writable attribute
- v1.2.x, Cannot add property Symbol(@@__YOU_CAN_NEVER_REMOVE_ARRAY_UNIQUE_TAG__@@), object is not extensible
  - One of workaround is do not set `type: array` in the schema.

**Comment by janryWang** [comment]
你是手动配置了immer setAutoFreeze为true了吗？

**Comment by chinesedfan** [comment]
@janryWang 不是，请仔细阅读上面拙劣的英文，原因是RN本地开发时为了避免开发者误修改组件state导致的。

**Comment by janryWang** [comment]
> @janryWang 不是，请仔细阅读上面拙劣的英文，原因是RN本地开发时为了避免开发者误修改组件state导致的。

等我下个版本发布你再试试哈
