### ISSUE TITLE
@formily/shared 的 toArr 方法入参为 Proxy 时在 iOS10 下的兼容性

### ISSUE THREAD

**Issue by linfaxin** [alibaba/formily#759]
@formily/shared 的 toArr 方法对于 ProxyObject 在 iOS10 下有兼容性问题。

iOS 下：
![image](https://user-images.githubusercontent.com/3705017/77825560-08a5ff00-7145-11ea-9d93-765724e71170.png)

Chrome 下：

![image](https://user-images.githubusercontent.com/3705017/77825649-9f72bb80-7145-11ea-9294-1408c1b42cb5.png)

**Comment by janryWang** [comment]
多谢反馈，提个PR？
