### ISSUE TITLE
带有initialValues的校验出现错误

### ISSUE THREAD

**Issue by wustcyl** [alibaba/formily#761]
设置有数值范围，而且有initialValues的一个NumberPicker，如果当重新输入的值和initialValues里面的值一样的话，那么就会校验失败报错，其他任何范围内的都没有问题。
[bug 复现](https://codesandbox.io/s/happy-archimedes-pjyy2)
当在输入框重新输入2的时候，就会出现校验失败。

**Comment by linfaxin** [comment]
+1 遇到了同样的问题。

复现：https://codesandbox.io/s/hopeful-http-qwbm5 （删除输入框内容再输入“1”，校验错误还在）
