### ISSUE TITLE
更新到最新版后 怎么表单变成一片空白了

### ISSUE THREAD

**Issue by yunuo-tech** [alibaba/formily#781]
1.0.8正常，更新到1.1.0后，所有表单都变成空白了，控制台也没报错，是新版有什么破坏性更新吗

**Comment by yunuo-tech** [comment]
经测试，在新版里，被FormCard包裹的表单都是空白的

**Comment by janryWang** [comment]
没法复现，至少给个codesandbox

**Comment by zhailb666** [comment]
我也遇到了，安装了@ant-design/compatible引起的
