### ISSUE TITLE
next input addonAfer属性在detail场景下渲染错误

### ISSUE THREAD

**Issue by fengxs269** [alibaba/formily#783]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

![image](https://user-images.githubusercontent.com/7137567/78630807-3ae5f800-78cd-11ea-8cae-11db76ac60e1.png)
![image](https://user-images.githubusercontent.com/7137567/78632470-aa5de680-78d1-11ea-88fb-c7a24fc5eb99.png)

description的maxTipsNum对于react-node无效

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox

**Comment by fengxs269** [comment]
import React, { Fragment, useState, useEffect } from 'react'
import { Form } from '@alife/ascp-design'
import {  Message, Button } from '@alifd/next'
import { useHistory, Link } from 'react-router-dom'

const { FormCard, FormSlot, FormItemGrid, FormTextBox,  FormButtonGroup  , FormLayout, Submit, Reset, Field } = Form



export default (props)=>{
   

    const defaultValues = {
itemSetId: 'xxxx'
    } 

    const ItemSetUrl =  <a href={`https://gdatacenter.cbbs.tmall.com/h/gitemset/choiceItemsetDetail?id=1111`} >去看看</a>  :
    return<Form
      labelCol={7}
      wrapperCol={12}
      maxTipsNum={200}
      editable={false}
      defaultValue={defaultValues}
    >
          <Field type="string" title="圈品集ID"  required name="itemSetId" x-props={{placeholder: '输入圈品集ID', addonAfter: ItemSetUrl}} />
    </Form>
}

**Comment by fengxs269** [comment]
https://codesandbox.io/s/suspicious-sea-pgnug?file=/src/App.js

**Comment by janryWang** [comment]
排查下来是使用的uform0.x，针对uform0.x可以考虑升级uform1.x
