### ISSUE TITLE
#787 引发的连锁问题

### ISSUE THREAD

**Issue by trexguo** [alibaba/formily#788]
https://github.com/alibaba/formily/blob/a2f7f33dcaf09dde659b2c7c92c9da9a98ce6faf/packages/react-schema-renderer/src/hooks/useSchemaForm.ts#L26

#787 未修复之前，使用 `babel-plugin-import`， import 走 `lib` 的时候，`component` 为 `undefined`，这里会报错，取 `styledComponentId` 之前需要先做检查

#787 merge 之后这个问题应该会消失，但是隐患依然存在。

**Comment by janryWang** [comment]
你的意思是，需要先判断component是否存在是吧

**Comment by trexguo** [comment]
> 你的意思是，需要先判断component是否存在是吧

是的
