### ISSUE TITLE
使用@formily/react-schema-renderer ，修复后在IE11上问题

### ISSUE THREAD

**Issue by qinfuji** [alibaba/formily#794]
#790 该问题发布在1.1.1-beta.0版本上，通过使用其实能在4-5秒渲染出来，但是在后续的20秒左右，全被计算所使用，导致IE11假死
[IE11运行地址](http://39.100.69.83:3200/main.html)

**Comment by janryWang** [comment]
我看版本没变化啊，确定是最新版？

**Comment by qinfuji** [comment]
确定是新版本，而且现象都不一样了

**Comment by janryWang** [comment]
加我微信吧，详细看看这个问题,janry_kk
