### ISSUE TITLE
跨越节点操作数据方法

### ISSUE THREAD

**Issue by TheRaindrop** [alibaba/formily#806]
数据结构：
[
  {
    a: { b: '' }
  }, {
    a: { b: '' } 
  }
]
在 formily 中我可以直接在 type='array' 里的 Field 中直接跳过 a，进而直接操作 b 吗，路径系统 name 支持 name="a.b" 这样的写法吗？试过，但是不支持这样的写法。

**Comment by janryWang** [comment]
等带上codesandbox，我再open
