### ISSUE TITLE
upload能否考虑支持达到最大数量限制时不显示上传按钮？

### ISSUE THREAD

**Issue by birdycn** [alibaba/formily#819]
您好，感谢您的作品。

upload能否考虑支持达到最大数量限制时不显示上传按钮？

在maxItems中也发现了一个问题，校验提示用的是maxLength的。

**Comment by janryWang** [comment]
upload组件要支持最大数量限制需要组件库来支持，formily不会做过多定制，maxItems校验规则是复用的max规则，所以提示是一样的，如果你希望不一样，可以自己定制自定义校验规则
