### ISSUE TITLE
upload类型组件引用即报错

### ISSUE THREAD

**Issue by zzkaqq** [alibaba/formily#844]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?
![image](https://user-images.githubusercontent.com/9392200/82006993-a9239480-969b-11ea-9d62-d87575fe889b.png)
![image](https://user-images.githubusercontent.com/9392200/82007003-afb20c00-969b-11ea-80cd-87cd3889b9d3.png)

将upload组件的引用移除即恢复正常

  - What is the expected behavior?
  - Which versions of Formily?

1.1.3

  - Did this work in previous versions of Formily?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codesandbox.io/s/1ry7zxv983) on CodeSandbox
.

**Comment by janryWang** [comment]
codesandbox里复现不了
