### ISSUE TITLE
时间范围选择 showTime 与 format 同时设置出现 bug

### ISSUE THREAD

**Issue by TopGrd** [alibaba/formily#880]
**Describe the bug**
DatePicker.RangePicker 当设置 x-component-props={{ showTime: true, format: 'YYYY-MM-DD HH' }}, 两者不能同时生效,并且会有显示BUG，日期后面带个小时，后面还有个时间

**To Reproduce**
https://codesandbox.io/s/epic-poincare-e7x2t?file=/index.js

**Expected behavior**
期望在显示时间的时候，可以正确设置日期值的格式

**Screenshots**
![image](https://user-images.githubusercontent.com/4202848/83475847-cccf4300-a4c1-11ea-87d0-3f26eafe99fa.png)
![image](https://user-images.githubusercontent.com/4202848/83475947-03a55900-a4c2-11ea-8cb0-20496f93d5ab.png)

**Comment by xianghongai** [comment]
formily 能将日期数据 Map 到 UI 中？比如航班信息之类的？
