### ISSUE TITLE
希望局部逻辑有更轻量的写法并且可以自动传入path

### ISSUE THREAD

**Issue by KyLeoHC** [alibaba/formily#895]
**Is your feature request related to a problem? Please describe.**
无

**Describe the solution you'd like**
我现在在写一些比较复杂的大表单的时候，有时候表单结构就比较复杂，而且现在官网的写法都得要自己维护那坨长长的path，比如：
```js
setFieldState('*.*.*.user.name', state => {
  FormPath.setIn(state, "visible", false);
});
```
如果某个字段名字一改，以上代码的路径也得改（虽然一般来说不会随便改，但确实偶尔会有这种情况），所以我希望能提供一种类似依赖注入的功能，可以自动收集并拿得到我想要的path，比如我现在自己简单实现的一个思路：[codesandbox demo](https://codesandbox.io/s/formily-x-effects-tkqfh?file=/src/App.js:936-1059)。

**Describe alternatives you've considered**

**Additional context**

**Comment by janryWang** [comment]
没明白问题在哪里，你是希望放弃以path为核心的联动模式？如果是这样的话，那formily做不到，因为从内核层就是基于path来的

**Comment by KyLeoHC** [comment]
> 没明白问题在哪里，你是希望放弃以path为核心的联动模式？如果是这样的话，那formily做不到，因为从内核层就是基于path来的

不是放弃，即希望还有一种可以省去自己维护path的写法，就像我demo里面的那种大概的思路，根据声明依赖并传入😂，直接取path。因为我遇到过一些字段联动比较多又嵌套比较深的情况，那个path维护起来还是挺头疼的（尤其恰好遇上字段名修改或者结构修改，有时候一不小心就忘记改了）。

**Comment by janryWang** [comment]
这个可以参考我在文档里逻辑管理那一篇，有专门讲联动复用的方案，主要是借助effect Hooks来做抽象，一层层抽象之后，其实可以提升很大的效率

**Comment by KyLeoHC** [comment]
> 这个可以参考我在文档里逻辑管理那一篇，有专门讲联动复用的方案，主要是借助effect Hooks来做抽象，一层层抽象之后，其实可以提升很大的效率

是指管理业务逻辑那一章吧？好像还是要手动写`*.*.*.user.name`这样的路径。我的述求其实简单来说，就是能有个免去手写这个path的特性（并不是要去掉手动写path的特性，毕竟某些情况下还是需要用到的）

**Comment by janryWang** [comment]
2.x中支持了相对路径，比如`.aa`这样的，就可以免去了重复写前段路径的繁琐
