### ISSUE TITLE
@formily/react is used inside of @formily/antd, but it is not a dependency

### ISSUE THREAD

**Issue by FredKSchott** [alibaba/formily#911]
On line: https://github.com/alibaba/formily/blob/master/packages/antd/src/components/FormMegaLayout/index.tsx#L4

However, this package is never mentioned in `@formily/antd` package.json: https://github.com/alibaba/formily/blob/master/packages/antd/package.json

This causes problems in the Pika CDN, which doesn't know which version to resolve the dependency to. It also causes problems in package managers like pnpm & Yarn v2 where they disallow an import like this without a matching package.json entry.

**Comment by quirkyshop** [comment]
#912 fix dependency of `@formily/antd` and `@formily/next`
