### ISSUE TITLE
不同浏览器下样式问题

### ISSUE THREAD

**Issue by imerovingian** [alibaba/formily#914]
**Describe the bug**
在不同浏览器上皆有样式失真问题，具体如下

ie11下效果
![ie11](https://user-images.githubusercontent.com/7758851/85942141-18a6c800-b95a-11ea-957d-1dd9cf5bc391.JPG)

chrome55下效果
![chrome55](https://user-images.githubusercontent.com/7758851/85942024-40496080-b959-11ea-9ae1-1be0160fac60.JPG)

Win10下EDGE效果
![win10_edge](https://user-images.githubusercontent.com/7758851/85942028-45a6ab00-b959-11ea-9075-b32eed3b0519.JPG)

没有问题的chrome83版本下效果
![chrome83](https://user-images.githubusercontent.com/7758851/85942032-4ccdb900-b959-11ea-99e0-a6f8031c5cae.JPG)

**Comment by quirkyshop** [comment]
#916
