### ISSUE TITLE
是否有计划升级styled-components的依赖

### ISSUE THREAD

**Issue by yuyiRai** [alibaba/formily#930]
项目中本地用了styled-components@5发现布局样式大部分失效

**Comment by janryWang** [comment]
有计划放弃styled-components

**Comment by missop** [comment]
赶紧放弃把，多余的东西

**Comment by lk0606** [comment]
> 有计划放弃styled-components

@janryWang 请教下，组件库中直接使用styled-components有遇到什么坑吗，有没有踩坑记录看看，有没有关于rerender问题
