### ISSUE TITLE
antd3中 FormMegaLayout中的自增table的每列受wrapperCol的设置变的很窄

### ISSUE THREAD

**Issue by xiaosu12138** [alibaba/formily#954]
**Describe the bug**
antd3中 FormMegaLayout中的自增table的每列受wrapperCol的设置变的很窄

**To Reproduce**
Please using Codesandbox
- [@formily/antd bug report template](https://codesandbox.io/s/antd3-megalayout-table-bug-uxd9s?file=/index.js)

**Expected behavior**
自增table中的每列的宽度不受FormMegaLayout中wrapperCol的影响

**Screenshots**
![image](https://user-images.githubusercontent.com/42687259/86763464-ee4fbb80-c079-11ea-8034-5360fcb86f1b.png)

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [chrome]
 - Version [83.0.4103.116]

**Comment by quirkyshop** [comment]
ArrayTable 默认每个元素都是撑满，所以父容器如果变窄，里面的内容就会变窄，和antd版本 V3 和 V4 是没有影响的。

如果要变宽一下，需要改变外部容器的宽度，不是BUG，先关闭了

**Comment by xiaosu12138** [comment]
> ArrayTable 默认每个元素都是撑满，所以父容器如果变窄，里面的内容就会变窄，和antd版本 V3 和 V4 是没有影响的。
> 
> 如果要变宽一下，需要改变外部容器的宽度，不是BUG，先关闭了

所以我需要在 ArrayTable 外部套两层 FormMegaLayout 吗，一层用于整体宽度，一层用于规定 ArrayTable 每个元素的宽度占比，像下边这样，因为ArrayTable的宽度会受 wrapperCol={15} 影响，所以需要再套一层吧wrapperCol设为24？
```
<FormMegaLayout labelCol={3} wrapperCol={15}>
    <FormMegaLayout wrapperCol={24} full label="用户列表Table">
        <Field
            name="userListTable"
            maxItems={3}
            type="array"
            x-component="ArrayTable"
        >
            <Field type="object">
                <Field name="username" type="string" title="用户名" />
                <Field name="relation" type="string" title="与本人关系" />
            </Field>
        </Field>
    </FormMegaLayout>
</FormMegaLayout>
```
