### ISSUE TITLE
希望能支持动态设置addOnAfter,addOnBefore等文案信息

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/formily#969]
希望能动态设置MeagLayout及下级Field x-mega-props的文案信息，addonBefore,addonAfter,description等。类似
    setFieldState('aaa',state=>{
      state['x-mega-props']['addOnAfter']='111';
    })

**Comment by janryWang** [comment]
应该是state.props['x-mega-props']['addonAfter']吧
