### ISSUE TITLE
FormMegaLayout 的full属性只有DatePicker才有效？

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/formily#974]
**Describe the bug**
FormMegaLayour full 表单组件是否撑满，实际使用中，只有DatePicker才有效，换做其他类型，不管full是否是true,实际效果下来都是撑满的

**To Reproduce**
Please using Codesandbox
官网布局示例

**Expected behavior**
full属性对其他组件类型也适用

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by quirkyshop** [comment]
这是取决于使用的组件库的能力，`full` 等同于手动加上 `width: 100% ` 的样式，如 fusion-next 大部分组件都是没有宽度100%的属性，full的适用性很高，如果antd的话，可能Input, Select 都有 `width 100%` 实际使用主要影响 *Picker 

如果需要针对 Input, Select 可以加上类似 width: auto 的样式, 但是这个动作让框架去做不太合适，因为面向的组件有太多，不确定因素比较多，先close掉这个issue。
