### ISSUE TITLE
next-components中针对upload组件的封装会导致字段丢失

### ISSUE THREAD

**Issue by pinkdoremi** [alibaba/formily#975]
**Describe the bug**
前提：
服务端返回的数据包含 {name, downloadURL, imgURL, id等等字段}，
操作步骤：
1. 上传1个文件之后
2. 再上传第二个文件。
此时状态：
【此时，第一个文件不包含 name, downloadURL, imgURL, id等等字段，第二个文件会包含 name, downloadURL, imgURL, id等等字段】

排查发现：
![image](https://user-images.githubusercontent.com/4578178/88513208-6d516780-d01a-11ea-8b87-212ff3d8d152.png)
normalizeFileList 这个方法针对返回值做了处理，第二次处理的时候，response 的东西就彻底丢失了。

**To Reproduce**
Please using Codesandbox
- [@formily/next bug report template](https://codesandbox.io/s/boring-dawn-tixps)
- [@formily/antd bug report template](https://codesandbox.io/s/lively-sky-pf5c3)

**Expected behavior**
保留服务端返回字段

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by janryWang** [comment]
1.x受限于扩展机制，2.x中已经支持二次封装
