### ISSUE TITLE
FormItem 的 dataSource 属性会被转换

### ISSUE THREAD

**Issue by hellohy** [alibaba/formily#982]
**Describe the bug**
自定义组件接受string[]类型的dataSource，注册后，传入的dataSource会被自动转换成 { label: string; value: string }[]。
源代码链接：https://github.com/alibaba/formily/blob/master/packages/react-schema-renderer/src/shared/connect.ts#L142  

**To Reproduce**
- [@formily/react-schema-render bug report](https://codesandbox.io/s/mystifying-wave-p5g3z)

**Expected behavior**
希望能开个口子，不转换dataSource属性

**Screenshots**
![image](https://user-images.githubusercontent.com/13514644/88901071-e4893480-d282-11ea-8bfe-2d0d39b5a4e7.png)

**Additional context**
如果限制如此，能否给个提示？

**Comment by janryWang** [comment]
用了connect就会默认有这个转换，如果你不希望被转换，可以给你的组件静态属性上挂一个isFieldComponent = true，这样它就不会被connect包装，然后你可以自己处理
