### ISSUE TITLE
setFormState会导致自增数组中的唯一标识丢失

### ISSUE THREAD

**Issue by wangmingxu** [alibaba/formily#991]
**Describe the bug**
当调用了setFormState设置form的values之后，自增列表中的唯一标识(symbol)会丢失，导致数组的删除/交换功能异常，field item的状态没有被正常交换

**To Reproduce**
Please using Codesandbox
- [@formily/antd bug report template](https://codesandbox.io/s/snowy-glade-hlu8v?file=/index.js)

**Expected behavior**
setFormState不会影响自增列表的功能

**Comment by janryWang** [comment]
复现路径描述一下

**Comment by wangmingxu** [comment]
看codesanbox里面的例子，点击setFormState的button之后，修改列表第一项为隐藏，然后删掉第一项，会发现异常

**Comment by janryWang** [comment]
哦，这个问题是因为你用的onFieldInputChange，这个是无法监听值变化的，你改为onFieldValueChange就可以了

**Comment by wangmingxu** [comment]
这里只是想说明setFormState和自增列表配合使用确实存在这样的缺陷，实际场景下总避免不了有些场景会使用setFormState

**Comment by janryWang** [comment]
> 这里只是想说明setFormState和自增列表配合使用确实存在这样的缺陷，实际场景下总避免不了有些场景会使用setFormState

我说的是跟setFormState没任何关系，是你在监听变化的时候，没用对监听事件

**Comment by wangmingxu** [comment]
既然说到监听的事件可以聊一聊另一个问题，也是我为什么会使用onFieldInputChange的原因，我的实际使用场景是自增列表里的每一个items都是一组联动的field，比如省市选择器，重选了省之后会清空市，每次进行数组操作(比如删除和交换顺序)都会导致所有顺序受影响的items的省市字段的onFieldValueChange被触发，进而触发清空市的操作，这个行为是不太符合预期的，所以选择了onFieldInputChange来绕过这个问题

**Comment by wangmingxu** [comment]
回到这个issue本身，setFormState会完成自增列表的唯一标识丢失，这个问题你可以从内部实现验证一下，随便找个arrayList log一下value即可复现，目测是因为setFormState走的下行同步逻辑没有做相关处理

**Comment by janryWang** [comment]
说的有道理，那我再排查一下吧
