### ISSUE TITLE
ArrayCard 完全定制标题

### ISSUE THREAD

**Issue by liunian** [alibaba/formily#995]
目前 ArrayCard 的标题，虽然可以使用 component props 中的 title 或 schema 中的 title，但默认会在前面添加序号（见下面代码）。

如果希望把序号放到后面来在中文语境下获得更好的表达（`卡片一`、`卡片二`比 `1. 卡片`、`2. 卡片` 更可读）。目前似乎只能完全定义一个列表组件。

希望，能提供方法来定制 title，比如类似于删除按钮那样使用 `renderTitle` 这样的方式来定制（保留原 title 的形式兼容老版本）。

下面是 `next` 系列的 ArrayCard的实现。

https://github.com/alibaba/formily/blob/eda988c05d518b0594a90532d94efdf8530040a4/packages/next-components/src/array-cards/index.tsx#L74-L78

**Comment by janryWang** [comment]
2.x已经支持

**Comment by ZhuSijing0607** [comment]
2.x的arrayCard可以支持从items中的数据读取动态配置tittle吗，在items层级中可以设置标题吗，没找到在哪设置
