### ISSUE TITLE
fieldState存在errors但是validate仍然通过

### ISSUE THREAD

**Issue by wangmingxu** [alibaba/formily#998]
**Describe the bug**
通过setFieldState的方式设置field为error状态，调用actions.validate()方法没有报错，而是走的校验成功逻辑
复现路径：
在codesandbox的例子中，先点击setFieldErrors按钮，再点击validate按钮，会发现进入了then的逻辑

**To Reproduce**
Please using Codesandbox
- [@formily/antd bug report template](https://codesandbox.io/s/charming-hypatia-biu6q?file=/index.js)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser [ stock browser]

**Additional context**

**Comment by janryWang** [comment]
联动校验和规则校验不是一个流程里的，validate函数只能处理规则校验

**Comment by wangmingxu** [comment]
> 联动校验和规则校验不是一个流程里的，validate函数只能处理规则校验
validate函数只处理规则校验的原因是什么？那联动校验这种场景产生的错应该怎么处理呢？希望能给出合理的解决方案

**Comment by janryWang** [comment]
可以在调用validate之后，使用actions.getFormState拿到整体form的errors，这个是做过合并的

**Comment by wangmingxu** [comment]
可以在validate内部实现里把这个事情做了，我理解这个不应该交给使用方去处理

**Comment by janryWang** [comment]
validate是处理规则校验，不是effects校验，两个不是一种行为模式

**Comment by wangmingxu** [comment]
对用户侧来说执行validate只希望知道当前整个表单的校验是否通过(no errors)，validate(现在的validate)=>执行x-rules=>errors和effect=>errors都只是创造errors的方式而已，现在有errors却能通过validate这个行为让人很迷惑，在文档里也没有对应的说明，踩坑的人会越来越多

**Comment by janryWang** [comment]
说的有道理，欢迎提个PR，可以在文档的validate API上加个提醒，只是针对规则校验生效，副作用校验不生效，总之validate这个API和副作用校验是不同的，两者完全不是一回事
